### ISSUE TITLE
Send a warning to log file signalling scrape target is defaulting to a deprecated spyname

### ISSUE THREAD

**Issue by shaleynikov** [grafana/pyroscope#1066]
Maybe we should signal somehow that it's defaulting to a deprecated spyName?

_Originally posted by @eh-am in https://github.com/pyroscope-io/pyroscope/pull/1060#discussion_r858890272_

**Comment by eh-am** [comment]
Maybe it's too much, but I was even considering something aggressive like showing in the UI "This spyName is deprecated, please use <link to the docs>". It's annoying but should force people to get rid of it.

**Comment by shaleynikov** [comment]
Another use case I have in mind is the following. User provide wrong configuration and scraper can't fetch spyname properly and fall into default value

At the moment I don't see any relation between spyname and data but coloring in the UI

**Comment by eh-am** [comment]
>At the moment I don't see any relation between spyname and data but coloring in the UI
I haven't looked at the backend code for this, but the question is more in the sense of whether the same application with 2 spyNames can be queried transparently. For illustration imagine that my application uses scrapename `scrape` until tuesday, then it starts using `gospy`. In that case I still want to query them as if they were the exact same spy.

But as I said, I haven't tested it. So maybe this is already solved.


> User provide wrong configuration and scraper can't fetch spyname properly and fall into default value
We could show something in the /discovery page I guess. That would be less intrusive.

**Comment by shaleynikov** [comment]
> I haven't looked at the backend code for this, but the question is more in the sense of whether the same application with 2 spyNames can be queried transparently. For illustration imagine that my application uses scrapename scrape until tuesday, then it starts using gospy. In that case I still want to query them as if they were the exact same spy (eg diffs should work).

I'm pretty sure general assumption is that it still need to be the same `spyName` on query. So 
> In that case I still want to query them as if they were the exact same spy (eg diffs should work).

this might be solved, but need to test.
