### ISSUE TITLE
Support for higher (than 10s) resolution for profiling data

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#122]
We've received some feedback about potentially increasing the minimum resolution for profiling data. Right now we're storing data in 10 second chunks. For more information on how it's stored see our [Storage Design doc](https://pyroscope.io/docs/storage-design)

I see a couple of ways we could implement this:
* allow users to modify the default hardcoded 10 second resolution
* store individual timestamps in trees along with samples

First approach is much simpler, it's almost as simple as making default resolution configurable. But then in extreme case when resolution is 10 ms it means that one tree will represent exactly one sample (at our default 100Hz sample rate) and that's not good.

**Comment by chadbrewbaker** [comment]
Noodling with this now: https://github.com/pyroscope-io/pyroscope/issues/130

When benchmarking you want high resolution. Not sure what Thomas is doing for optymize.cloud - I would pipe it to zstd (with a dictionary trained for pyroscope logs) in 50m chunks then exfiltrate it over the network or to disk.

--resolution=Xms would be my preferred flag. Default to your 10000ms is fine with me.

**Comment by CloudOfEquality** [comment]
Any idea to set Pyroscope resolution from the user perspective now? 
Seems still no access to that both in pyroscope command line tool and in the yaml config params😢
