### ISSUE TITLE
Fix styling of collapsed sidebar

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#1236]
Related to #819 
Currently collapsed sidebar has two small problems:

1. The little triangle doesn't match color of the highlighted sidebar item
2. the popup itself blends in a little bit with the background

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/23323466/178179423-2145cbb4-09bb-4570-b443-b9b20cfcee6e.png">

I think we should:
- [ ] add a dropshadow to the popup (similar to the styling of the app selector dropdown)
- [ ] Change the color of the popup (to the same color as the app selector dropdown)
- [ ] fix the color of the triangle

**Comment by asheerrizvi** [comment]
Hey @Rperry2174 I want to take this up 😃
