### ISSUE TITLE
Make the table tooltip percents bold

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#1363]
Currently in the tooltip its kind of hard to visually distinguish between the data and the tooltip percentage that is attached to the data:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/23323466/183344537-93e5c13f-f5a1-44b7-982c-df427fa499e4.png">

We should make it so that the percentages and the labels in the header of the table are bold to make it easier to distinguish between the perentages and the data 

- *% of total cpu*
- *29.53%*

Also we should be consistent between the title and the table row and add a space between the value and the percent

**Comment by athulmekkoth** [comment]
Can i work on this?
