### ISSUE TITLE
Make dropdowns consistent

### ISSUE THREAD

**Issue by eh-am** [grafana/pyroscope#1436]
In the time range picker
![image](https://user-images.githubusercontent.com/6951209/186178454-4156e60e-d205-40bc-b4a3-3162d266dea0.png)

Add a blue highlight, similar to
![image](https://user-images.githubusercontent.com/6951209/186178522-98d0dc5b-d7aa-43a2-a9f6-5e70ee807d3b.png)

---
Also do the same for Tag Explorer
https://user-images.githubusercontent.com/6951209/186179050-8abc1b44-5dd8-46dc-857c-5db0a2a421c7.mp4

If possible a `checked` option to `MenuItem` that adds that + checkmark would be nice.

**Comment by Rperry2174** [comment]
fixed in #1395
