### ISSUE TITLE
Wrong Time in Java Wall mode profiling

### ISSUE THREAD

**Issue by netamego** [grafana/pyroscope#1440]
Hi,

Duration is wrong when profiling java app with wall mode enabled. Same por cpu profile dashboard when wall is enabled.

Env:
 pyroscope-0.21.0-1
 java-agent-0.8.1

![Wall-Time](https://user-images.githubusercontent.com/10206580/186595255-0ff59cc5-77af-4b2c-973b-d51d4ee5fb04.png)

Thanks a lot.

**Comment by Rperry2174** [comment]
Hi @netamego do you have multiple agents reporting to this Pyroscope instance? The time inside of the flamegraph is CPU time, so if you have multiple agents running in parallel then their aggregate CPU time can be more than the actual amount of time that has elapsed

**Comment by netamego** [comment]
Hi @Rperry2174 

Nop. Only one agent. I confirmed that from pyroscope server with next command:

tcpdump -i eth0 -s 0 -A 'port 4040 and (tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x504f5354)' | egrep 'IP |ingest\?name=myappnameinpyroscope'

Thanks.

**Comment by netamego** [comment]
Same behaviour for itimer. Somtimes duplicate methods...

![image](https://user-images.githubusercontent.com/10206580/186703936-65048ef4-5285-4d14-b753-3a92dd2b0838.png)

**Comment by korniltsev** [comment]
Reproduced the issue
https://flamegraph.com/share/2bd03bb0-2570-11ed-93ce-4e4125c43ec1

Took a quick look and I think in wall mode async-profiler samples thread every 100us, and we count as 10ms
https://github.com/jvm-profiling-tools/async-profiler/blob/master/src/wallClock.cpp#L33 Also not all threads but at most 8 per 100us

I am looking into how to deal with it.

**Comment by korniltsev** [comment]
I took a closer look and my previous guess was wrong. If you have a lot of threads sleeping it is expected to have a lot of wall time, lets say I profile one hour with 100 threads sleeping, I'd expect to see 100 hours in profile.
Could you please share wrong cpu, wall, itimer flamegraphs, not screenshots. Also can you please share thread list (for example "jstack -l $pid") or at least number of threads.

Speaking of duplicates, does it happen regularly? Any tips on how to reproduce? What jvm version? What pyroscope java configuration do you use? Do you use collapsed or jfr?
