### ISSUE TITLE
pip package (pyroscope-io) not working

### ISSUE THREAD

**Issue by benerain** [grafana/pyroscope#1500]
I don't know if I used the tool correctly. i can connect to the pyroscope server by run
 `pyroscope server` in one terminal window and run 
 `sudo pyroscope -application-name='ride-share' exec python server.py runserver` in another window. 
but if i use the pyroscope-io package just run the code like below:
```py
import pyroscope
import time

pyroscope.configure(
  application_name = "my.python.app", # replace this with some name for your application
  server_address   = "http://172.0.0.1:4040", # replace this with the address of your pyroscope server
)

while True:
  time.sleep(1)
```
and then i type localhost:4040 in my browser. i ll find localhost refuse my connection.(i didn't  run `pyroscope server` in terminal, but if i run, there still no app called "my.python.app")
Am i use the tool in a wrong way? 
mac os 12.0.1 M1 chip

**Comment by Rperry2174** [comment]
Hi @LiYuJia1202 ! Sorry for the confusion here, but if you have the pip package installed, you will not need to run `pyroscope exec` 

instead you should be able to run your program like normal `python server.py runserver`. Just make sure to configure the options properly. 

Here is an example in our repo:
- command: https://github.com/pyroscope-io/pyroscope/blob/main/examples/python/rideshare/django/docker-compose.yml#L6
- configuration: https://github.com/pyroscope-io/pyroscope/blob/main/examples/python/rideshare/django/app/hello_django/settings.py#L141-L152

**Comment by LiYuJia1202** [comment]
Hi @Rperry2174, thank you for your reply! I am not very familiar with Docker for now and I just want it work on my computer.  I recorded my operation on the screen, and I knew that there must be something wrong with me, but I didn't know which step. Here is the code I ran in the video. I just wonder why the name "test.app" doesn't appear in my pyroscope drop-down menu
```py
import pyroscope

def work(n):
	i = 0
	while i < n:
		i += 1

def fast_function():
	with pyroscope.tag_wrapper({ "function": "fast" }):
		work(20000)

def slow_function():
	with pyroscope.tag_wrapper({ "function": "fast" }):
	    work(80000)

if __name__ == "__main__":
    pyroscope.configure(
	application_name  = "test.app",
	server_address = "172.0.0.1:4040")
    while True:
        fast_function()
        slow_function()

```


[demo1.mov.zip](https://github.com/pyroscope-io/pyroscope/files/9571113/demo1.mov.zip)

**Comment by LiYuJia1202** [comment]
By the way, here is the log file after I set enable_logging= True. It seems that py_spy is working but it just don't show up in localhost's pyroscope drop-down menu
[test.log](https://github.com/pyroscope-io/pyroscope/files/9571759/test.log)

**Comment by korniltsev** [comment]
172.0.0.1 is some private network address, are you sure you have pyroscope server there?
Try to use localhost 127.0.0.1
Also you need specify http address, not just host:port
I modified your example a little and it worked.
```
diff --git a/testpyro.py b/testpyro.py
index 6a511fc..4fcfeda 100644
--- a/testpyro.py
+++ b/testpyro.py
@@ -19,8 +19,9 @@ def slow_function():
 
 if __name__ == "__main__":
     pyroscope.configure(
+               enable_logging=True,
         application_name="test.app",
-        server_address="172.0.0.1:4040")
+        server_address="http://127.0.0.1:4040")
     while True:
         fast_function()
         slow_function()
```
https://flamegraph.com/share/ce36469b-34c9-11ed-832b-1ea3ff17b40b

**Comment by LiYuJia1202** [comment]
Thank you so much for your reply～ it works！

**Comment by LiYuJia1202** [comment]
And i already install the newest version of pyroscope
<img width="567" alt="截屏2022-09-15 下午5 22 57" src="https://user-images.githubusercontent.com/21291632/190367329-f8d3c6d1-2942-4590-b3da-36828d952388.png">

**Comment by korniltsev** [comment]
Do you see http requests if you sniff trafic? for example like `sudo tcpdump -i lo  -f 'port 4040' -w -`
Could you attach server logs? Do you see something like ""POST /ingest?name=test.app.cpo" there? Are you running low on disk space?

**Comment by LiYuJia1202** [comment]
when i run `sudo tcpdump -i lo -f 'port 4040' -w -` :
<img width="477" alt="截屏2022-09-15 下午6 47 54" src="https://user-images.githubusercontent.com/21291632/190385074-16bdb232-df6f-41e3-aeb2-0a86e2e0e6c9.png">

the server log like this:
<img width="564" alt="截屏2022-09-15 下午6 47 08" src="https://user-images.githubusercontent.com/21291632/190384933-c89c4f7e-6f31-41c5-ae51-de06239386ea.png">
i see nothing like ""POST /ingest?name=test.app.cpo" 
my disk space is still adequate:
<img width="486" alt="截屏2022-09-15 下午6 49 33" src="https://user-images.githubusercontent.com/21291632/190385389-d6a1382f-23e2-43e9-a0a2-f850cae577c2.png">

**Comment by korniltsev** [comment]
lo: no such device exists - that is wired
try `sudo tcpdump -i any  -f 'port 4040' -w -`
`ifconfig`
`ping localhost`

**Comment by korniltsev** [comment]
oh you are on mac, loopback is probably "lo0"

**Comment by korniltsev** [comment]
also try running server with --log-level=debug

**Comment by korniltsev** [comment]
also please try adding at the beginning `logging.getLogger().setLevel(logging.DEBUG)` and also remove `with pyroscope.tag_wrapper({"function": "fast"}):` because it is very noisy in debug mode

**Comment by LiYuJia1202** [comment]
@korniltsev @Rperry2174 Thank you for your patience. i did what you said.
<img width="1440" alt="截屏2022-09-16 上午11 23 56" src="https://user-images.githubusercontent.com/21291632/190551474-c0d335e3-9fd2-4c42-b935-bb6acdac2de5.png">
i attached three files: pyroscopetest.pcap , server.log and terminal.log
[attachFile.zip](https://github.com/pyroscope-io/pyroscope/files/9580483/attachFile.zip)

this is the full code i run above:
```py
import pyroscope
import logging
logging.getLogger().setLevel(logging.DEBUG)

def work(n):
	i = 0
	while i < n:
		i += 1

def fast_function():	
	work(20000)

def slow_function():
	work(80000)

if __name__ == "__main__":
    pyroscope.configure(
        enable_logging=True,
	application_name  = "test.app",
	server_address="http://127.0.0.1:4040")
    while True:
        fast_function()
        slow_function()
```
and still no name called test.app showed up
<img width="1438" alt="截屏2022-09-16 上午11 28 57" src="https://user-images.githubusercontent.com/21291632/190552099-d261074f-1170-4826-9922-71a382f63815.png">

**Comment by korniltsev** [comment]
I've tried your code and it works on my machine(amd linux) so I guess it is ok
OK, pyspy is not sending http requests.
It should be something like this
```
2022-09-16T05:56:30.000Z INFO  Pyroscope::Session          > Creating Session
 2022-09-16T05:56:30.000Z INFO  Pyroscope::Session          > Sending Session: 1663307780 - 1663307790
 2022-09-16T05:56:30.000Z TRACE reqwest::blocking::wait     > (ThreadId(6)) park without timeout
 2022-09-16T05:56:30.000Z TRACE reqwest::blocking::client   > (ThreadId(23)) start runtime::block_on
 2022-09-16T05:56:30.004Z TRACE reqwest::blocking::wait     > wait at most 10s
 2022-09-16T05:56:30.004Z TRACE reqwest::blocking::wait     > (ThreadId(6)) park timeout 9.99999963s
 2022-09-16T05:56:30.004Z DEBUG reqwest::connect            > starting new connection: http://127.0.0.1:4040/
 2022-09-16T05:56:30.004Z TRACE mio::poll                   > registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
 2022-09-16T05:56:30.004Z TRACE want                        > signal: Want
 2022-09-16T05:56:30.004Z TRACE want                        > signal found waiting giver, notifying
 2022-09-16T05:56:30.004Z TRACE want                        > poll_want: taker wants!
 2022-09-16T05:56:30.004Z TRACE want                        > signal: Want
 2022-09-16T05:56:30.004Z TRACE want                        > signal: Want
 2022-09-16T05:56:30.004Z DEBUG reqwest::async_impl::client > response '200 OK' for http://127.0.0.1:4040/ingest?name=test.app.cpu&from=1663307780&until=1663307790&format=folded&sampleRate=100&spyName=pyspy
 2022-09-16T05:56:30.004Z TRACE reqwest::blocking::client   > closing runtime thread (ThreadId(23))
 2022-09-16T05:56:30.004Z TRACE reqwest::blocking::client   > signaled close for runtime thread (ThreadId(23))
 2022-09-16T05:56:30.004Z TRACE reqwest::blocking::client   > (ThreadId(23)) Receiver is shutdown
 2022-09-16T05:56:30.005Z TRACE reqwest::blocking::client   > (ThreadId(23)) end runtime::block_on
 2022-09-16T05:56:30.005Z TRACE mio::poll                   > deregistering event source from poller
 2022-09-16T05:56:30.005Z TRACE want                        > signal: Closed
 2022-09-16T05:56:30.005Z TRACE reqwest::blocking::client   > (ThreadId(23)) finished
 2022-09-16T05:56:30.005Z TRACE reqwest::blocking::client   > closed runtime thread (ThreadId(23))
 2022-09-16T05:56:30.005Z TRACE pyroscope::session          > SessionManager - Session sent
 ```
 I will try to reproduce on apple silicon.

**Comment by LiYuJia1202** [comment]
Okay，if you fix it, please let me know

**Comment by korniltsev** [comment]
yes it is not apple chip problem. on intel same behavior

**Comment by LiYuJia1202** [comment]
@korniltsev  Hi, I'm glad you successfully replicate the issue. So if it is not a chip problem, is it a mac problem? Or some system setting issues? Hope you will solve this problem soon~

**Comment by bck01215** [comment]
Also affected
