### ISSUE TITLE
Allow editing/deleting an annotation

### ISSUE THREAD

**Issue by eh-am** [grafana/pyroscope#1526]
Instead of "Add Annotation" we could have "Edit Annotation" and "Delete Annotation" buttons

![Kapture 2022-09-19 at 18 34 45](https://user-images.githubusercontent.com/6951209/191123840-9fde6560-8fd2-42c3-8ca9-46eff11797e7.gif)

For edit it should be just populating existing `Popover` with the same data (since we have upserts).
For deletion we need to add a `DELETE` endpoint to the backend first.

**Comment by Rperry2174** [comment]
Might be worth waiting until we implement these for more options on where we put these buttons
https://github.com/pyroscope-io/pyroscope/pull/1489#issuecomment-1244580421
