### ISSUE TITLE
How to profile Openjdk8 app with eBPF agent (k8s)?

### ISSUE THREAD

**Issue by shyamjos** [grafana/pyroscope#1528]
How to profile an Openjdk8 app running in kubernetes (EKS) using eBPF agent ?  how to deal with stacktraces full of [unknown]s ?

Where to install debug packages ? on host machine or inside java app container ?

**Comment by korniltsev** [comment]
I dont think we have plans to do ebpf-java profiling from grafana agent yet.
We hava pyroscope.java grafana agent component which is using async-profiler though

https://grafana.com/docs/agent/next/flow/reference/components/pyroscope.java/
