### ISSUE TITLE
Add ability to set sample rate in ingestion path

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#1564]
Important — this is not the same as profiler's internal sampling rate (typically 100Hz).

---

The idea here is to add ability to set sampling rate on the client. Say you have 100 servers and you set sample rate to 10 — this means you're sampling data from every 10th server, or 10 servers out of a 100.

Then, when we get data on the backend we can multiply all numbers in a profile by 10 and get the total numbers to be close to the real numbers.

Honeycomb has a similar concept: https://docs.honeycomb.io/manage-data-volume/sampling/

---

This will require changes in a few places:
* [ ] ingestion endpoint — we'll need to add a new parameter that clients can pass, that basically becomes a multiplier for all numbers in the profile.
* [ ] changes in the integrations. I could see us going in a few different directions with this:
  * [ ] make sample rate work across servers. Each server would get a unique ID that we could use to then apply a sample rate. This has a pro which is it's easy to implement, but it has a con that if you only have 1 server and sample rate of say 10, you're most likely never going to get any data.
  * [ ] make sample rate work across time — e.g profile 10 seconds, then wait for 90 seconds.
  * [ ] or leave the implementation of the exact sampling logic to users, and only just have a way to set the sample number in the integrations
  * [ ] or we could have a combination of these

RE integrations, I propose that we start with go integration, test it out with a few large users and then over time port the changes to other integrations as well.

**Comment by petethepig** [comment]
For now we should start with the backend part.

**Comment by kolesnikovae** [comment]
- I'm thinking about one more reserved label.
 - It would be nice to distinguish this sampling and profiling sample rate unambiguously. Or, should we eliminate the distinction (can be hard, I guess)?
 - As for support for the average aggregation – I think there should be a very small change in the storage layer that would ensure that we store proper number of writes in the segment node (a simple increment as of now). Same for exemplars: we should store the sample rate along with the exemplar data.
 - It seems we need to _compensate_ sample rate at read time.
