### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#166]
![image](https://user-images.githubusercontent.com/662636/116189764-4aa1cb80-a6de-11eb-922f-59f385e446f0.jpeg)

### TODO

* [ ] make pyroscope compile on windows. This shouldn't be too complicated but will take some time for sure as there's a lot of moving parts in the current build process, e.g pyspy, rbspy — I think in v1 we can disable them though. We could also skip this for now and start with macOS and linux
* [x] make exec command work on Windows. I remember this behaving differently between linux and macOS so I imagine we're gonna open a can of worms once we add Windows support https://github.com/pyroscope-io/pyroscope/blob/main/pkg/exec/cli.go#L94

**Comment by closedLoop** [comment]
Is anyone working on python support here?  I'm receiving this error message:
```bash
pyroscope adhoc python mycode.py
Error: spy "pyspy" is not supported. Available spies are: dotnetspy```

**Comment by iWhyDuck** [comment]
Any plans for this issue? :)

**Comment by giard-alexandre** [comment]
Why was this issue marked as closed? As far as I can tell, it's still impossible to run Pyroscope agent on Windows...

**Comment by giard-alexandre** [comment]
Why was this marked as closed? It's currently not possible to profile an app on Windows...
