### ISSUE TITLE
Have 2 separate types for Profile before and after delta-diffing

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#1682]
Currently a `Profile` can represent both data before delta diffing and after delta diffing. This poses challenges, when adding new functionality (particularly `flamegraph/src/convert` functions), as it's always unclear whether you should or should not be performing the conversion.

I'm thinking maybe we could solve this problem with TS type system. We could have a `Profile` before delta diffing and a `Profile` after delta diffing, let's say `CompressedProfile` and `Profile`. This way it would always be clear what kind of profile you're dealing with and weather or not you have to perform delta diffing.

@eh-am What do you think about this?

**Comment by eh-am** [comment]
And their shape (ie their fields) is the same right? IMO that's a perfect case for nominal typing (https://basarat.gitbook.io/typescript/main-1/nominaltyping).

As an example we started using it here https://github.com/pyroscope-io/pyroscope/blob/af6ced651ad5f86e037e8b9961a1f91b1f6a1b40/webapp/javascript/models/query.ts
