### ISSUE TITLE
pyroscope contains the so binary problem

### ISSUE THREAD

**Issue by chentao-kernel** [grafana/pyroscope#1701]
Hi guys!
I download the source code, and with the command "make build-release", i found the pyroscope contains the so
![image](https://user-images.githubusercontent.com/86768822/201285020-b7babb01-78c0-4e27-aa0f-49aaee1dcbfa.png)
But the release binary no need so binary
![image](https://user-images.githubusercontent.com/86768822/201285485-c2c984aa-18a2-470a-9b7b-30c7276eee32.png)
How can i remove the so，edit the Makefile？
Looking forward your reply，thank you！

**Comment by chentao-kernel** [comment]
I do not use the container compile, i see the dockerfile there is a static flag, so i must use the container compile?

**Comment by korniltsev** [comment]
If I assume `libbpf.so` and `libbcc-syms.so` is what causing your inconvinience
I believe with the following change you can link to static versions of those libs.
```
diff --git a/Makefile b/Makefile
index a4adfeb0..df050b7f 100644
--- a/Makefile
+++ b/Makefile
@@ -42,8 +42,8 @@ ALPINE_TAG =
 ifneq (,$(findstring ebpfspy,$(GO_TAGS)))
        EXTRA_CGO_CFLAGS := $(EXTRA_CGO_CFLAGS) -I$(abspath ./third_party/libbpf/lib/include) \
                -I$(abspath ./third_party/bcc/lib/include)
-       EXTRA_CGO_LDFLAGS := $(EXTRA_CGO_LDFLAGS)  -L$(abspath ./third_party/libbpf/lib/lib64) -lbpf \
-               -L$(abspath ./third_party/bcc/lib/lib) -lbcc-syms -lstdc++ -lelf -lz
+       EXTRA_CGO_LDFLAGS := $(EXTRA_CGO_LDFLAGS)  -L$(abspath ./third_party/libbpf/lib/lib64) ./third_party/libbpf/lib/lib64/libbpf.a \
+               -L$(abspath ./third_party/bcc/lib/lib) ./third_party/bcc/lib/lib/libbcc-syms.a -lstdc++ -lelf -lz
        THIRD_PARTY_DEPENDENCIES := $(THIRD_PARTY_DEPENDENCIES) build-profile-bpf build-bcc build-libbpf
 endif
```
Alternatively you can remove shared libs and it should link to static libs.
```
make build-third-party-dependencies && find third_party/ -name "*.so" -delete
```
Also if you don't need `ebpfspy` you can just build with `ENABLED_SPIES_RELEASE=none` without linking to those libs at all.

If my assumption is wrong and you just want full static build, this is supported only in alpine environment, which we use in docker.

**Comment by chentao-kernel** [comment]
Thanks, solved it with your method.
