### ISSUE TITLE
Selecting too small periods on the main timeline results 500 error

### ISSUE THREAD

**Issue by Ivanikitin** [grafana/pyroscope#1744]
https://user-images.githubusercontent.com/35915834/202829871-a13e8a94-4dfb-4fd6-941e-e200ed2dd941.mp4

**Comment by pavelpashkovsky** [comment]
seems like if `continuous.from` and `continuous.to` have the same timestamp values, app becomes unusable

https://user-images.githubusercontent.com/7372044/205053731-3e33208b-6759-474e-b2a7-11e56a2d20b2.mp4

**Comment by pavelpashkovsky** [comment]
@eh-am , @Rperry2174 is it worth fixing? if so what the expected UI when user selected too small period?
