### ISSUE TITLE
setting base-url  causes blank pages.

### ISSUE THREAD

**Issue by dumbFeng** [grafana/pyroscope#1781]
I used '--base-url' flag like the following command:
```
$ pyroscope server --base-url /pyroscope
```
Then I accessed web ui, but I got a blank page:
![image](https://user-images.githubusercontent.com/33219197/205035417-d33040f4-465f-4ece-9e4a-dbedfe5402a9.png)

**Comment by eh-am** [comment]
Hey @dumbFeng! Yeah this is tricky, without more info the best I can suggest you right now is to have a look at the example here https://github.com/pyroscope-io/pyroscope/tree/main/examples/base-url.
