### ISSUE TITLE
After upgrade to pyroscope-0.34.1-1 seems there are problems with retention policies

### ISSUE THREAD

**Issue by netamego** [grafana/pyroscope#1793]
Hi,

In our production environment we have started to see next error after upgrade pyroscope server to 0.34.1-1:

```
[root@myserver ~]# systemctl status pyroscope-server.service
? pyroscope-server.service - Open source continuous profiling software
   Loaded: loaded (/usr/lib/systemd/system/pyroscope-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-12-05 20:56:27 CET; 1 day 14h ago
     Docs: https://pyroscope.io/
 Main PID: 25562 (pyroscope)
    Tasks: 14 (limit: 294571)
   Memory: 38.4G
   CGroup: /system.slice/pyroscope-server.service
           +-25562 /usr/bin/pyroscope server

Dec 07 11:23:01 myserver pyroscope[25562]: time="2022-12-07T11:23:01.694475" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="d2_myserver_3.lock_count{}"
Dec 07 11:23:09 myserver pyroscope[25562]: time="2022-12-07T11:23:09.900733" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="myserver.BPEL.alloc_in_new_tlab_bytes{}"
Dec 07 11:23:09 myserver pyroscope[25562]: time="2022-12-07T11:23:09.900782" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="myserver.BPEL.alloc_outside_tlab_bytes{}"
Dec 07 11:23:09 myserver pyroscope[25562]: time="2022-12-07T11:23:09.900796" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="myserver.BPEL.cpu{}"
Dec 07 11:23:09 myserver pyroscope[25562]: time="2022-12-07T11:23:09.900808" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="myserver.BPEL.lock_duration{}"
Dec 07 11:23:16 myserver pyroscope[25562]: time="2022-12-07T11:23:16.084630" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="AdminServer.alloc_in_new_tlab_bytes{}"
Dec 07 11:23:16 myserver pyroscope[25562]: time="2022-12-07T11:23:16.084675" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="AdminServer.alloc_outside_tlab_bytes{}"
Dec 07 11:23:16 myserver pyroscope[25562]: time="2022-12-07T11:23:16.084697" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="AdminServer.itimer{}"
Dec 07 11:23:16 myserver pyroscope[25562]: time="2022-12-07T11:23:16.084711" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="d2_myserver_2.lock_duration{}"
Dec 07 11:23:16 myserver pyroscope[25562]: time="2022-12-07T11:23:16.084728" level=error msg="error happened while ingesting data" file=" storage/queue.go:86" error="could not write because of retention settings" key="d2_myserver_2.wall{}"
```

Our retention policy (while storage in S3 is being developed ;)) is:

```
cat /etc/pyroscope/server.yml
---
retention-levels:
 0: 72h  # 3 days
 1: 144h # 6 days
 2: 216h # 9 days
```

PD: Keep going. You are doing incredibly well. Pyroscope is a great software.

Best regards.

**Comment by netamego** [comment]
Hi,

Thank you so much for your help. You are right. From Pyroscope server:

```
tcpdump -i ens192 -s 0 -A 'port 4040 and (tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x504f5354)' | egrep 'ingest\?name=myserv1|ingest\?name=myserv2'
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens192, link-type EN10MB (Ethernet), capture size 262144 bytes
E....B@.@..     .............Z.;Eo.$P.r..e..POST /ingest?name=myserv1.app&units=samples&aggregationType=sum&sampleRate=100&from=1670416480&until=1670416490&spyName=javaspy&format=jfr HTTP/1.1
E....I@.@.'....b........!.5g..`.P....&..POST /ingest?name=myserv2.app&units=samples&aggregationType=sum&sampleRate=100&from=1669647200&until=1669647210&spyName=javaspy&format=jfr HTTP/1.1
```

myserv1 have correct epoch time (1670416480) but myserv2 have epoch in the past (1669647200 (28 Nov)). I don't understand this behaviour, but seems take place long time ago. I have tested with pyroscope server versions 0.21.0-1, 0.31.0-1 and 0.34.1-1 and the behaviour is the same. 

 We have 10 servers with diferent java apps and all of them with pyroscope-java-agent 0.10.2 (latest) and we have this strange behaviour with two server. Both servers have the correct date/hour. Both have ntp configured.

 The profiling works as expected in this two servers (no doubt) but at some point the problem took place. We are going to reboot one of the affected apps and I will keep you informed.

– How often do you see these errors?
Every minute. Always for the same apps. Not all aaps are affected.
– Is it possible that there is a time sync issue on the client side?
No. 
– Do you use any kind of persistent queue like Kafka as an intermediate storage? Such errors might happen on data backfill.
No
– Were these settings in use before the update?
Yes. But my mistake. Seems the problem is not the upgrade. Tested with older pyroscope versions (0.21.0-1, 0.31.0-1) and same behaviour,

Best regards.

**Comment by kolesnikovae** [comment]
Hi @netamego, thank you very much for the detailed answer! One more question: does this wrong timestamp change or it is always the same?

@korniltsev, may I ask you to look into the issue?

**Comment by korniltsev** [comment]
@netamego Do you have two apps on the same server with wrong and correct time? Can you share your java agent configuration? jvm version, vendor, environvment (docker/os). Do you have application logs with correct time from the app with wrong profiling time?

**Comment by netamego** [comment]
Hi,

Environment:

Pyrocope Server: 0.34 (but same proble with previous versions) running on RHEL 8.6 Kernel 4.18.0-372.26
Pyroscope Agent: Java agent 0.10.2 in WSO2 EI-Business-Process 6.2.0 running on jdk1.8.0_171 (same problem with Java agent 0.10.2 in Weblogic AdminServer running on jdk1.8.0_281) 

Problem:
`Do you have two apps on the same server with wrong and correct time? `
 Yes. java-agent is always sending, exactly, the same timestamp in the past. Reboot pyroscope-server doesn't solve anything. Reboot java process solves the problem. 
`Do you have application logs with correct time from the app with wrong profiling time?`
Yes. Correct time in app logs. 
`Can you share your java agent configuration?`
Sure.
```
export PYROSCOPE_SERVER_ADDRESS=http://mypyroscopeserver:4040
export PYROSCOPE_APPLICATION_NAME=myserver.BPEL
export PYROSCOPE_FORMAT=jfr
export PYROSCOPE_PROFILER_ALLOC=0
export PYROSCOPE_PROFILER_LOCK=0
export PYROSCOPE_PROFILER_EVENT=wall
```

At some point we have had problems with the pyroscope server (high cpu consumption) and we have had to restart it. Maybe those reboots don't sit well with the java agent? But why does it only happen with some apps?

Thank yoy so much for your help.

Best regards.

**Comment by korniltsev** [comment]
> Yes. java-agent is always sending, exactly, the same timestamp in the past.
Oh that is weird. Can you check http response status code  /body? Does it get 200 or smth else?
According to code If an ingestion request gets a response with >=400 it will be retried until succeeds. That could explain a stale profile. I'd like to know if this is actually the case and if yes - what is the reason for non200 response.

I guess we should not retry infinitely, I will add an option to configure maximum retry
