### ISSUE TITLE
The self-owned agent can connect to the pyroscope server.

### ISSUE THREAD

**Issue by Mr-dot-lu** [grafana/pyroscope#1797]
We need to connect our own agent to the pyroscope server.
Our own agent produces flames in svg format.
I hope someone can guide us on how to do it, thank you very much!

**Comment by eh-am** [comment]
Hey!

Your agent will need to push data in a format pyroscope recognizes.
Easiest way is to use `collapse/folded` format, but we also accept pprof/JFR. For more info see the ingestion page:
https://pyroscope.io/docs/server-api-reference/#ingestion

Just out of curiosity, can you disclose which agent/language are you using?

**Comment by Mr-dot-lu** [comment]
We agent used eBPF
