### ISSUE TITLE
Very High CPU Usage by JFR Parser

### ISSUE THREAD

**Issue by netamego** [grafana/pyroscope#1798]
Hi,

 We have pyroscope server version 0.34 that we only use to ingest jfr profiling data from 18 java apps through java-agent 0.10.2. In all apps the java agent configuration is the same:

```
export PYROSCOPE_SERVER_ADDRESS=http://mypyroscopeserver:4040
export PYROSCOPE_APPLICATION_NAME=myserver
export PYROSCOPE_FORMAT=jfr
export PYROSCOPE_PROFILER_ALLOC=0
export PYROSCOPE_PROFILER_LOCK=0
export PYROSCOPE_PROFILER_EVENT=wall
```
So that's a good amount of data.

The problem is that cpu consumption of JFR Parser is very very high.

Next screenshot from vmstat, top and lscpu

![image](https://user-images.githubusercontent.com/10206580/207836558-da2d86ae-9025-406f-9b0d-bf00bf52b291.png)

Next screenshot from pyroscope:

![image](https://user-images.githubusercontent.com/10206580/207837010-3973f48b-eb2e-466e-9b31-3e4264f4a24e.png)

Is there any room for improvement in cpu consumption of jfr parser?

Thank you so much for your great work and product.

Best regards.

**Comment by Rperry2174** [comment]
hey @netamego any chance you could send us the actual flamegraph here either in pprof or flamegraph.com link? 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/23323466/213589291-7c3a420b-b60d-4acd-9d2c-367ec18fba2c.png">

It would help us to debug and look for optimizations
