### ISSUE TITLE
pyroscope server errors out when run as a normal user on Ubuntu/Fedora

### ISSUE THREAD

**Issue by AulonSal** [grafana/pyroscope#181]
## How to reproduce
Run `pyroscope server` as a non-pyroscope, non-root user after installing the rpm or deb.

### Expected behaviour:
```
INFO[0000] starting HTTP server  
```
### Actual behaviour:
```
panic: mkdir /var/lib/pyroscope/main: permission denied

goroutine 1 [running]:
github.com/pyroscope-io/pyroscope/pkg/cli.startServer(0xc0000c22c0)
	github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:330 +0x81e
github.com/pyroscope-io/pyroscope/pkg/cli.generateRootCmd.func1(0x1624200, 0xc000022090, 0xc00000e090, 0x0, 0x0, 0xc00005ef00, 0x0)
	github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:265 +0x5f
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc0000b38c0, 0x1624200, 0xc000022090, 0x0, 0x0)
	github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:153 +0x1b2
github.com/peterbourgon/ff/v3/ffcli.(*Command).Run(0xc0000b3c30, 0x1624200, 0xc000022090, 0x0, 0x0)
	github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:157 +0x125
github.com/peterbourgon/ff/v3/ffcli.(*Command).ParseAndRun(0xc0000b3c30, 0x1624200, 0xc000022090, 0xc00000e090, 0x1, 0x1, 0x8, 0xc0000c22c0)
	github.com/peterbourgon/ff/v3@v3.0.0/ffcli/command.go:169 +0x7e
github.com/pyroscope-io/pyroscope/pkg/cli.Start(0xc0000c22c0, 0x15, 0xc0000c22c0)
	github.com/pyroscope-io/pyroscope/pkg/cli/cli.go:323 +0x98
main.main()
	github.com/pyroscope-io/pyroscope/cmd/pyroscope/main.go:13 +0x56
```

## Reason for incongruity:
`$LOG_DIR` and `$DATA_DIR` are owned by *pyroscope* and have permissions set to 755 but the `pyroscope` binary is run as the current user, who does not have write access to the directories.
https://github.com/pyroscope-io/pyroscope/blob/5372d782e0794bd5b3cc46356b31d1445798d348/scripts/packages/post-install.sh#L40-L43

## Possible fixes (that I can think of)
1. `chown` the  `pyroscope` binary to *pyroscope* and set the SUID bit on it in https://github.com/pyroscope-io/pyroscope/blob/main/scripts/packages/post-install.sh.
```bash
function set_binary_permissions {
  chown pyroscope: "$BIN_DIR/pyroscope"
  chmod u+s "$BIN_DIR/pyroscope"
}
```

2. Relax the permissions on `$LOG_DIR` and `$DATA_DIR`

I don't have anything else installed that goes with the way of doing things in the first fix so I don't know if it has an obvious security flaw that I'm missing.

Of course you could simply run it as the *pyroscope* user or use the systemd service but I believe the intent is to have the ability to run the server from your normal user, based on https://pyroscope.io/docs/.

**Comment by AulonSal** [comment]
My bad, closed by mistake.

**Comment by petethepig** [comment]
@AulonSal Thanks for reporting this, I'll take a look at it soon.

**Comment by AulonSal** [comment]
Actually, neither of the above mentioned potential fixes work:
1. Setting the SUID bit on the pyroscope binary and making it be owned by user _pyroscope_ does not work as, for example, ebpfspy needs to be run as root.
2. Relaxing permissions only on `$LOG_DIR` and `$DATA_DIR` does not work as all the directories and files inside (all that I have seen) are created only writable by the user who originally wrote them, thus if you relax the permissions on, say, `$DATA_DIR`, whichever user first runs `pyroscope server` is the only one who'll be able to run it in the future unless all contents of `$DATA_DIR` are deleted first.

The above findings were motivated by @abeaumont's [comment on the pyroscope aur package](https://aur.archlinux.org/packages/pyroscope-bin#comment-851872), (I'd previously applied the above mentioned 1st fix to it).

Possible fixes I can see as of now:
1. Make all files in `$DATA_DIR` group-writable in the source code and set the SGID bit on the pyroscope binary, alternatively, make them world writable and you don't need to mess with the binary.
2. Split the server and client binaries, and set the SUID bit on the server binary - this seems like too big a change to solve a minor problem.
3. Change nothing in the  packaging or source code and tell users to either always run the server through the systemd service (or analogues) or as the pyroscope user manually (e.g `sudo -u pyroscope -E pyroscope server`).

**Comment by abeaumont** [comment]
Thanks for coming back to this @AulonSal, and for the nice proposals. 

In my opinion fix number 2 is the one that makes more sense, as the server and clients have inherently different requirements, and coupling them generates this kind of problem. Yet, it also makes simple operations harder, so it's a bigger decision. Points 1 and 3 are simpler ones, and thus easier to apply. The first one seems more user-friendly, as we don't need to bother the user with these details, they can be solved by the packager, so maybe we can go with that one?

**Comment by abeaumont** [comment]
After giving this a bit more thought, maybe option 3 is the best approach. The packaging system provides a systemd unit which is the expected way to run the service, and thus, users shouldn't be expected to run the server manually in those cases (as with usual databases servers, etc.).

So I think the current way packaging works (including the latest changes in the aur package) is fine, which then raises another question:

> Of course you could simply run it as the pyroscope user or use the systemd service but I believe the intent is to have the ability to run the server from your normal user, based on https://pyroscope.io/docs/.

I think we should fix this. It'd be great if you would report anything that gives this impression in the docs.
