### ISSUE TITLE
Wasm

### ISSUE THREAD

**Issue by gedw99** [grafana/pyroscope#184]
I am increasingly compiling golang code to run as wasm using the golang and tinygo compiler

It would be awesome to be able to profile code that is compiled this way .

With tinygo you can’t use reflection or network golang api calls but running in a web worker is fine and how I generally run golang wasm in a browser or IOT device.

anyways I think it’s an interesting use case an challenge.

Here is a example approach. See makefile 

https://github.com/jerson/openpgp-mobile/tree/flatbuffers

—-

As an aside it’s also possible for the actual profiling web gui to be make to use wasm too these days without too much effort

**Comment by chadbrewbaker** [comment]
https://bellard.org/jslinux/vm.html?url=alpine-x86.cfg&mem=192  even curl works :)

WASM profiling with perf: 
https://rustwasm.github.io/book/reference/time-profiling.html
