### ISSUE TITLE
Support for ZTS version (phpspy does not have it)

### ISSUE THREAD

**Issue by senseicoder** [grafana/pyroscope#1926]
Hi, 

We want to try Pyroscope on our PHP servers, but we only have PHP with ZTS enabled, so Pyroscope show this error
```
popen_read_line: No stdout; cmd=objdump -Tt /proc/22313/root//usr/sbin/php7.4-fpm | awk '/ executor_globals$/{print $1; exit}'
get_symbol_offset: Failed
```
which come from phpspy
```
cedric@prefnttstb1:~$ sudo ./phpspy --limit=1000 --pid=22312
popen_read_line: No stdout; cmd=objdump -Tt '/proc/22312/root//usr/sbin/php7.4-fpm' | awk '/ executor_globals$/{print $1; exit}'
get_symbol_offset: Failed
```

We are investigating (using another PHP profiler, deactivating ZTS, ...), but do you have a solution about this ?

**Comment by korniltsev** [comment]
Let's wait for reply in upstream https://github.com/adsr/phpspy/issues/133

Do you use threads? and want to profile them?
