### ISSUE TITLE
70% of Pyroscope CPU usage spent of verifying API keys

### ISSUE THREAD

**Issue by ignaloidas** [grafana/pyroscope#1951]
I've set up a small deployment to check the performance of a couple small services I run/develop. It's currently handling about 50 incoming profiles per minute (excluding the ones it generates itself), all using the same API key for authentication, and it ends up spending about 70% of it's CPU time verifying that key again and again.

![pyroscope server cpu_2023-05-17_0055-to-2023-05-17_0655](https://github.com/grafana/pyroscope/assets/16557741/bce1c840-c2c3-4eb8-95ba-ebc574c45bf8)
https://flamegraph.com/share/c05e0492-f466-11ed-bb01-4a9f46d3c4af

For what it's worth, I feel like there's three issues in this. For one, there's a authentication caching layer, and it's not working for some reason. For second, the default bcrypt profile is fairly expensive, and probably could be dialed back to the minimum allowed one, since these are completely randomly generated keys, with whole 256 bits of entropy, trying to brute-force them would be futile. But thirdly, I'm not sure that API keys need to have password-grade hashing. If the database leaked, with unhashed passwords and API keys, the passwords could be very worrisome for the users, because of password reuse and similar concerns, while the API keys only give access to a single service, and are unique to it. I'd still hash them, but I don't think there's any need for expensive hash functions that protect against attacks against low entropy passwords - there's 256 bits of entropy here after all, just a single SHA256 hash will do, to stop against the rare attack where an attacker only has a read-only view of the database.

For completeness, I'm running Pyroscope v0.37.2 on Debian 11 Bullseye installed from the official deb package, with ingestion and internal authentication enabled.

**Comment by kolesnikovae** [comment]
Hello @ignaloidas! Thank you for the detailed description of the problem and for sharing your thoughts.

I find all your concerns very well founded. I especially want to emphasize that using the password hashing function for API keys is an unfortunate choice, a mistake. Eventually the problem can be solved by switching to a more suitable hash function, and SHA256 seems like a reasonable option. If you want to contribute to the project, I will be happy to provide you with all the necessary assistance.

As a workaround (see https://github.com/grafana/pyroscope/pull/1952), the following options should be considered:
 - BCrypt cost can be set to a lower value (defaults to 10, min 4): e.g `--auth.auth.api-key-bcrypt-cost=8` might be sufficient.
 - API key cache TTL can be increased (defaults to 1m): `--auth.ingestion.cache-ttl=5m`.
