### ISSUE TITLE
javaagent 方式启动  启动成功过没有在 ui 看到启动的应用

### ISSUE THREAD

**Issue by zhanghongwang** [grafana/pyroscope#1955]
` java -jar wf-baccarat-ws-1.0-SNAPSHOT.jar -javaagent:pyroscope.jar -DPYROSCOPE_APPLICATION_NAME=myapp -DPYROSCOPE_SERVER_ADDRESS=http://172.20.13.160:4040
`

**Comment by chengjoey** [comment]
Do you see logs starting with `Error uploading snapshot:` in your application?

**Comment by zhanghongwang** [comment]
感谢 已经可以了 是一个莫名奇妙的问题 无法复现
