### ISSUE TITLE
alloc_space max than inuse_space 

### ISSUE THREAD

**Issue by cao2358** [grafana/pyroscope#1976]
with version: v0.37.2
at my graph , the alloc_space is less than inuse_space , why ?
for alloc_space vs inuse_space
![image](https://github.com/grafana/pyroscope/assets/25002557/8a64a706-dd0d-47b5-906e-c0191660944a)
![image](https://github.com/grafana/pyroscope/assets/25002557/bd5ffb96-e3df-411c-9e9b-7ce5f2643fdd)

here is a bug?

**Comment by kolesnikovae** [comment]
Hello @cao2358,

Thank you for reporting the issue! These are quite different measurements:
- `alloc_space` indicates memory allocated from the program start (cumulatively), like a prometheus counter.
- `inuse_space` reports memory allocated on heap but not yet released, the value is instant, as a prometheus gauge.

For convenience, Pyroscope server calculates deltas of `alloc_*` profiles, but that requires two consecutive profiles, therefore the difference in the screenshot is understood and expected if you've only sent just one profile. Also, please note that `inuse_*` profiles are averaged, therefore the difference with `alloc_*` profiles will be more and more prominent over time

**Comment by cao2358** [comment]
Does this mean that the histogram for alloc_* shows new allocations over the previous one? And inuse_* represent the average memory usage?

**Comment by kolesnikovae** [comment]
Sorry for the delay!

> Does this mean that the histogram for alloc_* shows new allocations over the previous one? And inuse_* represent the average memory usage?

- Yes, correct, `alloc_*` show a _sum_ of new allocations over the previous one. It is like if we applied Prometheus [increase](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) function.
- `inuse_*` histograms show a _sum_ of instant actual values. This is different to the aggregation of the flamegraph (which is average, indeed). This inconsistency might be misleading, however we believe that this is better for detecting memory leaks – an averaged histogram is tend to "hide" gradually increasing values, therefore a memory leak would likely be unnoticed.

**Comment by kolesnikovae** [comment]
If you don't mind I close the issue. Please feel free to re-open it if you have any questions
