### ISSUE TITLE
huge VIRT mem allocate by pyroscope server

### ISSUE THREAD

**Issue by ingangi** [grafana/pyroscope#1978]
![image](https://github.com/grafana/pyroscope/assets/9778842/eb004b43-feaa-4161-b286-5ad3d0b34f07)

**Comment by kolesnikovae** [comment]
Hello @ingangi. This is due to how Go runtime manages memory – you can find more here https://go.dev/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory. I'm closing the issue. Please feel free to re-open it if you have any questions
