### ISSUE TITLE
Will there be a new helm chart since the acquisition?

### ISSUE THREAD

**Issue by nabadger** [grafana/pyroscope#1983]
Hi, 

Currently the helm chart is available at https://github.com/pyroscope-io/helm-chart 

I'm wondering if there are any plans to change this to be more inline with existing grafana helm charts?

If so, do you imagine there would be a migration path available? We're wondering whether to move forward with pyroscope-io or whether to hold-off and wait for any changes in this area (given it's a recent acquisition).

Thanks

**Comment by Rperry2174** [comment]
Hi @nabadger sorry for the inconvenience and thanks for the patience. 

> I'm wondering if there are any plans to change this to be more inline with existing grafana helm charts?

Yes definitely

> do you imagine there would be a migration path available

Also yes we will do our best to have a migration path that causes minimal disruption

We are in the process of [merging the repos](https://github.com/grafana/phlare/pull/808) right now and are aiming to have all this complete by mid-august. This will be when we release Pyroscope 1.0. 

We've merged them _internally_ (we run the merged version in [Grafana Cloud](https://grafana.com/blog/2023/06/07/continuous-profiling-now-in-public-preview-in-grafana-cloud/)) and are working through the logistics of how we can bring this merged version into the OSS world with minimal disruption to existing Phlare _and_ Pyroscope. 

In the meantime, if you want to reach out on the [#pyroscope channel in the Grafana slack](https://grafana.slack.com/archives/C049PLMV8TB) or DM happy to discuss your orgs situation in more detail and help you make the decision on where / when to get started

**Comment by nabadger** [comment]
Awesome, thanks for the quick reply :)

**Comment by salarali** [comment]
Any new updates on when the 1.0 release will be happening?

**Comment by Rperry2174** [comment]
Aiming for tomorrow!
