### ISSUE TITLE
ebpf profiling does not work in kind

### ISSUE THREAD

**Issue by korniltsev** [grafana/pyroscope#1994]
-pid=host does not work in kind and it runs in a separate pid namespace

https://github.com/kubernetes-sigs/kind/issues/3182

If the pods are running as privileged(I am not 100% sure) we may consider adding an option to try to escape the pid namespace with https://blog.trailofbits.com/2019/07/19/understanding-docker-container-escapes/ for smoother dev experience

**Comment by korniltsev** [comment]
we should improve and autodetect if not running root pid namespace

**Comment by simonswine** [comment]
We now compare the PID in ebpf with the same PID namespace that is used in userspace 

#3008
