### ISSUE TITLE
Update presets on time picker 

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#1999]
The initial time picker had a bunch of defaults that we copied from Grafana's old time picker. In reality, it is definitely not recommended for people to query, for example, 5 years of profiling data. 
<img width="428" alt="image" src="https://github.com/grafana/pyroscope/assets/23323466/d33094ac-3ece-476d-8cc6-689165c0c178">

We should update the date picker to look / function similar to the new grafana date picker except limit the presets to no longer than   6 months (maybe even shorter) 
<img width="513" alt="image" src="https://github.com/grafana/pyroscope/assets/23323466/f5796ce8-2111-479d-9fb5-c111abf94f86">

**Comment by darrenjaneczek** [comment]
I am considering that in a pyroscope environment, the current picker can be used.
When in a Grafana environment, the Grafana picker can be used instead.

**Comment by darrenjaneczek** [comment]
@Rperry2174 , are we satisfied by 
- https://github.com/grafana/pyroscope/pull/2008
to close this?
