### ISSUE TITLE
Add support for exporting profiles from UI

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#2022]
In https://github.com/grafana/pyroscope we have support for exporting data in different formats:
![image](https://github.com/grafana/phlare/assets/23323466/ef00aeb2-a73e-4148-92b1-268f0d0ec165)

However, in phlare we do not have the same functionality because [these export functions](https://github.com/grafana/pyroscope/blob/main/webapp/javascript/components/ExportData.tsx) are not available on the backend

related: https://github.com/grafana/grafana/issues/71705
https://github.com/grafana/grafana/pull/61537

**Comment by cyriltovena** [comment]
This is done but there's an issue blocking pprof https://github.com/grafana/phlare/issues/793
