### ISSUE TITLE
Use the physical block plan for all query endpoints

### ISSUE THREAD

**Issue by cyriltovena** [grafana/pyroscope#2049]
Right now the store-gateway can have multiple replicated block and we deduplicate them while streaming data. 

but we should instead request all block ULID for a given range and query accordingly ingester and storegateway within using `queryStoreAfter`. This will also allow us to deduplicate blocks from the start.

**Comment by simonswine** [comment]
This is now tracked in more detail by: https://github.com/grafana/pyroscope/issues/2674
