### ISSUE TITLE
In-memory querier panic on access to row groups

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/pyroscope#2054]
It's been reported that in-memory head querier may panic on access to row groups:

<img width="1281" alt="image" src="https://github.com/grafana/phlare/assets/12090599/5bb646e0-c89e-46e9-80b5-0e4daa268fd3">

Supposedly, the bug was introduced in https://github.com/grafana/phlare/commit/06093f837bc6dc77cc862e8293afd3d6be28c3c3

**Comment by cyriltovena** [comment]
Haven't seen it for a while!
