### ISSUE TITLE
[DOC] Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [grafana/pyroscope#2086]
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know). This kind of information is important for the end-users.

Thanks in advance!

**Comment by knylander-grafana** [comment]
I've opened a new doc issue to capture updating the hardware requirements in the docs: https://github.com/grafana/pyroscope/issues/3490
