### ISSUE TITLE
Downsampling

### ISSUE THREAD

**Issue by cyriltovena** [grafana/pyroscope#2118]
The goal is to reduce the resolution and denormalize the data to speed up large time range queries.

# Type of downsampling

There's 3 different way we can do downsampling. Each of them have different pros and cons, and they can be applied together (combined), they are not exclusive. 

## By time

Similar to [Thanos downsampling](https://thanos.io/v0.8/components/compact/), downsampling by time means aggregating the data from the same series across time.

For example the current minimal resolution is 15s for a unique series (it can even be lower with FaaS profiling), downsampling by time is aggregating into lower resolution 1m and 5m each series so that when we query for large time range we can uses those aggregation to fulfil the request without affecting the result.

This can speed up both metric and flamegraph queries. 

For metric queries it depends on the step being used by the application, usually the step increase as the timerange increase, for 30d the step is 5m, for 12h the step is 15s. This would effectively reduce the data we have to query by 20x for 30d queries.

For flamegraph queries, there is no step parameter and savings will be only based on the query selected range. However the aggregation cannot aggregate away stacktrace ID since the break down is required to form/render the flamegraph. 

**However we might want to consider truncating unique stacktrace samples per aggregated datapoint. Something to explore and so may be configurable**

All of this means, we will have to apply downsampling to the `TotalValue` and the list of stacktrace samples `Samples` as defined below. 

https://github.com/grafana/pyroscope/blob/31ec2d03fbdfa0f47cf2fc896fd6dd8c066abf39/pkg/phlaredb/schemas/v1/profiles.go#L43C34-L44

```go
		phlareparquet.NewGroupField("TotalValue", parquet.Encoded(parquet.Uint(64), &parquet.DeltaBinaryPacked)),
		phlareparquet.NewGroupField("Samples", parquet.List(sampleField)),
```

I'll share more ideas/exploration in the [storage](#storage) part.

## By dimension

While downsampling by time will help when querying large time range, if within that time range there's a lot of unique series like millions pods, then we'll still have to pull a lot of machine resources to answer that query.

We could also downsample by dimensions aka series labels, for instance summing for each unique service_name, and then for each service_name+pod, etc....

> **Similarly we should downsample also by stacktraces tags like SpanID, and any user defined one.**

While those are interesting, they also are less flexible, it will be hard to support all combinations user will want. I still think we can make a good guess or make the list of label to aggregate on configurable per tenant.

For example storing hourly flamegraph per service_name could drastically improve Single View and Tag Explorer initial load up.

<img width="2250" alt="image" src="https://github.com/grafana/pyroscope/assets/1053421/2d9cb59f-bebc-4da8-97da-127baf71527e">

In fact I think this type of aggregation will be super useful for bird eyes view of your system and again I think we should highly consider truncation of stacktraces.

## By symbol

Last but not least, downsampling by symbol could also be extremely useful, in fact this how original Pyroscope was since it was not storing the line number of each stacktraces.
Right now when rendering flamegraph we're not actually using line number, and each new version of an applications will generate new line number and mapping, increasing the amount unique stacktraces.

While I think the high resolution per line is important for future feature like Code View https://github.com/grafana/pyroscope-squad/issues/97. We should store a version of samples without that level of details, e.g the unicity of a stacktrace becomes only it's function names and not its mapping, versions, line numbers.

This can also be used to speed up metrics queries with filtering per function name. https://github.com/grafana/pyroscope/issues/2228

# When should we downsample 

Since downsampling remove the unicity of profiles received, we can't deduplicate using downsample data and will have to query the original data.

In my opinion, this means there's no reason to downsample pre-compaction level 3 when the data is fully deduplicated from replication. In fact I think in the future we should strive to reduce the timerange where we deduplicate the data  (currently [now-4h] we'll query ingesters data and deduplicate), we should strive to have compacted data as soon as possible and smaller ingestion blocks.

# Storage

We use parquet to store each profile, usually spaced by 15s (single row). Because how we access the data, using labels selector to match series and timerange, the data is stored sorted first by series and then time.

For better separation of concerns, we should store downsampling data into different file for each resolution. The filename could hint the resolution and type if any. We will still need `SeriesIndex` and `Timestamp` column, although the timestamp doesn't need nanoseconds precision, the duplication of data should be fairly small since both can easily be delta and double delta encoded.

**Comment by kolesnikovae** [comment]
Thank you @cyriltovena for the detailed description of the issue.

 * I would prioritize in this order:
   - By dimensions (including sample-level dimensions)
   - By time
   - By symbol
 * I agree that downsampling should happen on/after L3 compaction.
 * I'm less confident about the data location:
    - If we want to aggregate by time, and the aggregation window exceeds the block duration (which will likely take place), it's easier to have a new block.
    - Allows us to downsample downsampled blocks easily (assuming blocks are immutable).
    - It's easier to implement more flexible retention policies (assuming blocks are immutable). 
 * I'm also wondering how the downsampled data should be combined. Having a block per downsampling type is probably too wasteful (the curse of dimensionality), therefore we probably want to combine those.
 * Regarding stack traces cardinality reduction: I'm not very sure if this will be very effective once we add breakdown by version and line number. I assume that users will _always_ want to use it :)

---

We probably need to consider impact of the optimisation based on the query type:
 - Time series: the query result is a set of grouped time series. We do not access profiling data, only the `Total` column.
 - Stack traces: the query result is a profile (flamegraph/pprof).
 - Labels/Series: not applicable.

For a query that spans period **P** and affects **S** series, the number of rows/profiles to be processed can be expressed via `S * (P / W)`, where **W** is the interval the profiles are collected.

By downsampling we increase **W**:
 - For time series queries the limit is determined by `min_step` - the minimal distance between two data points – order of minutes, while **W** typically lies within 15-60s. Time series queries are typically fast enough if the blocks are compacted. Therefore, I assume we should focus on profile queries solely.
 - For profile queries, **W** is limited to the block duration.

So, for example, if we were to query (all data) an 1h block with 1000 series collected with 15s interval (240 profiles per series), we'd need to process 240K profiles. Impact of downsampling is linear: in the best case (W = 1h) we only need to process 1K profiles. In the worst case W = 1m (?), we process 60K profiles. It's worth noting that:
 - Aggregated profiles are obviously bigger (they include all the samples from the source data set) and their processing takes more time.
 - On average, for each query there are two blocks for each shard that we need to handle without downsampling at least partially: the begging and the end of the time range.

---

By dimensionality reduction we decrease **S**: the lower boundary is, probably, 1 – the `service_name` label, so our equation reduces to `P / W` = 240 – the best case. However, if the query includes a _reduced_ label, we ought to process the source data (240K, unless downsampled). The optimisation works both for time series and profile queries.

If we analyze user queries we'll likely find that those are fall into two categories: 
 - service-wide profile. Might be a very heavy query that the optimisation is aimed at.  
 - service-instance-wide profile (e.g., a pod). Should not cause performance issues.

Ideally, dimensionality reduction should be adaptive (like Mimir's adaptive metrics). In the first version we could probably configure this manually, given that we can make some educated guesses on which series we want to keep.

**Comment by cyriltovena** [comment]
Closing for now.
