### ISSUE TITLE
Investigate IteratorResult pool usage and performance

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/pyroscope#2137]
I noticed rather suspicious code path that might affect the read path performance – I suspect that we use the `query.iteratorResultPoolGet` pool incorrectly:
![image](https://github.com/grafana/pyroscope/assets/12090599/85b26f72-f3a0-4f02-ad80-560f64d9de61)

**Comment by kolesnikovae** [comment]
I guess it is caused by `defer` in the loop:
https://github.com/grafana/pyroscope/blob/e17b0d0164e0e0806c33a2c12de9b63f6b1e872a/pkg/phlaredb/query/iters.go#L457-L467

**Comment by simonswine** [comment]
Good catch, yes that wouldn't work like I imagined it 🙁
