### ISSUE TITLE
Remove label names filtering in the querier once f25 is rolled out

### ISSUE THREAD

**Issue by simonswine** [grafana/pyroscope#2167]
This doesn't seem to make problems with older ingesters, that do not know about the LabelNames field

Connect Go via JSON, is more strict about unknown fields.

_Originally posted by @simonswine in https://github.com/grafana/pyroscope/pull/2163#discussion_r1272343339_

**Comment by aleks-p** [comment]
This seems to be fixed or no longer relevant.
