### ISSUE TITLE
Function metric

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/pyroscope#2228]
It would be useful to visualize the time series for a particular function (a node of the flamegraph). Ideally, grouping by labels should be supported as well. Currently, the metric always shows the "total" value.

![image](https://github.com/grafana/pyroscope/assets/12090599/c063fd72-b2db-4035-97c1-450521f45eec)

**Comment by cyriltovena** [comment]
We should consider extending the current SelectSeries to include a list of function to filter the result with. `[]string`

We should most likely only resolve symbols when the filtering is provided.
