### ISSUE TITLE
Allow series/profileTypes/labelValues to be querier from block/store

### ISSUE THREAD

**Issue by simonswine** [grafana/pyroscope#2230]
We currently only support label retrieval from the Head of each ingester, we should add `start`/`end` parameters to those methods and support querying blocks on ingesters and store-gateways. 

We need to implement this for these APIs:

- [x] Series labels https://github.com/grafana/pyroscope/pull/2431
- [x] Label names https://github.com/grafana/pyroscope/pull/2498
- [x] Label values https://github.com/grafana/pyroscope/pull/2594
- [x] Profile types https://github.com/grafana/pyroscope/pull/2617

**Comment by bryanhuhta** [comment]
With https://github.com/grafana/grafana/pull/77523 merged, this is complete.
