### ISSUE TITLE
The continuous increase of dicts and segments directory data causes disk alarms

### ISSUE THREAD

**Issue by ly0511** [grafana/pyroscope#2237]
#### Describe the bug

I only deployed the server for pyroscope. Since August 7th, I suddenly found that the data in the dicts and segments directories in the pod continued to increase, causing the disk to generate alarms. May I ask why this happened, is there any adjustment, and how to solve it

#### To Reproduce

1. Start Phlare (SHA or version)
2. Perform Operations(Read/Write/Others)

#### Environment

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm, jsonnet]

**Comment by kolesnikovae** [comment]
Duplicates #2263
