### ISSUE TITLE
MergeProfilesStacktraces fails with i/o timeout when querying data from 3 hosts @ 100k Hz for 3h, even with a large cluster

### ISSUE THREAD

**Issue by luisgerhorst** [grafana/pyroscope#2273]
#### Describe the bug

When running Pyroscope in the default cluster configuration from the Helm chart, I get the following error when querying the data for 3 hosts (each being profiled at 100k Hz by Grafana Flow Agent) for 3 hours or more:

```
level=warn caller=gokit.go:83 caller=http.go:197 traceID=48..cd msg="GET
       /pyroscope/render?format=json&from=now-3h&query=process_cpu%3Acpu%3Ananoseconds%3Acpu%3Ananoseconds%7Bservice_name%3D%22Linux%22%7D&until=now (500) 30.019743983s Response: \"unknown:
       {\\\"code\\\":\\\"internal\\\",\\\"message\\\":\\\"stream error: stream ID 7; INTERNAL_ERROR; received from peer\\\"}\\n\" ws: false; Accept: */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.5;
       Content-Length: 0; Forwarded: for=<...>;host=<...>.com;proto=https; Referer:
       http://localhost:4040/?query=process_cpu%3Acpu%3Ananoseconds%3Acpu%3Ananoseconds%7Bservice_name%3D%22Linux%22%7D&from=now-3h; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent:
       Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0; Via: HTTP/1.1 <...>; X-Amzn-Trace-Id: Root=1-<...>; X-Forwarded-Port: 443; "
level=warn caller=gokit.go:83 caller=http.go:178 traceID=48...cd msg="POST /ingester.v1.IngesterService/MergeProfilesStacktraces 44.367168526s, error: 2 errors: i/o timeout; i/o timeout ws: false; Accept-Encoding:
       identity; Connect-Protocol-Version: 1; Content-Type: application/connect+proto; Uber-Trace-Id: <...>:0; User-Agent: connect-go/1.9.0 (go1.19.12); X-Scope-Orgid: anonymous; "
```

In the UI, I get `503 Service Unavailable` for the request to `/pyroscope/render`.

Crucially, the problem can not be resolved by doubling the cluster size and cpu/memory requests/limits.

#### To Reproduce

1. Start Phlare (https://github.com/grafana/pyroscope/commit/29fb2b36d1224826d8abb58e6129932865764987), configure it to use native S3 as the object store and an EFS mount as persistent storage for ingesters.
2. Submit data from 3 hosts with the flow agent configured with `sample_rate = 99991` and `collect_interval = "1ns"`.
3. Query the data in the Pyroscope UI single view for 3 hours.

#### Expected behavior

The query should work, at least when scaling the cluster / node size.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

When querying data for 6h (> 4h = `query_store_after`), I also get

```
level=warn caller=gokit.go:83 caller=http.go:178 traceID=5d<...>a8 msg="POST /storegateway.v1.StoreGatewayService/MergeProfilesStacktraces 37.293213364s, error: 2 errors: i/o timeout; i/o timeout ws: false;
       Accept-Encoding: identity; Connect-Protocol-Version: 1; Content-Type: application/connect+proto; Uber-Trace-Id: 5d<...>7:0; User-Agent: connect-go/1.9.0 (go1.19.12); X-Scope-Orgid:
       anonymous; "
```

**Comment by korniltsev** [comment]
> sample_rate = 99991 and collect_interval = "1ns".
Am I understanding correctly that you try to  collect stacktraces 99991 times per second, which is every ~10us and trying to upload stacktraces every 1ns?

**Comment by kolesnikovae** [comment]
Hello @luisgerhorst, thank you for filing the issue! Do you by any chance happen to have a profile from the ingester / store-gateway or maybe a trace of the query?

**Comment by kolesnikovae** [comment]
Also, just to clarify: what does happen if you query e.g last 15 minutes of data? Does the query return results or fails as well?

**Comment by luisgerhorst** [comment]
Thanks for the quick response!

> Am I understanding correctly that you try to collect stacktraces 99991 times per second, which is every ~10us and trying to upload stacktraces every 1ns?

Yes exactly, however the latter does not really happen I think because the agent only starts the 1ns timer after having finished the last POST request. With this, the agent consumes ~1.5 CPUs. The machine is still useable despite the sampling at 99991Hz, I have not verified whether the kernel actually samples that often (but I see a few samples in every POST). My goal was to simulate the amount of data submitted by 3k servers or more.

> Also, just to clarify: what does happen if you query e.g last 15 minutes of data? Does the query return results or fail?

When I query the data for 1 hour or less it succeeds. In rare case 3h also works but I have never seen 6h work.

> Do you, by any chance, happen to have a profile from the ingester / store-gateway or maybe a trace of the query?

Currently not, I was planning to extend the logging in `block_querier.go`'s `MergeProfilesStacktraces()` to get that but any hints on how to point Jaeger (I guess) at the cluster would also be very appreciated. I looked into the Go opentracing package Pyroscope uses but it appear deprecated.

**Comment by kolesnikovae** [comment]
Thank you for doing this @luisgerhorst! 

> Yes exactly, however the latter does not really happen I think because the agent only starts the 1ns timer after having finished the last POST request. With this, the agent consumes ~1.5 CPUs. The machine is still useable despite the sampling at 99991Hz, I have not verified whether the kernel actually samples that often (but I see a few samples in every POST). My goal was to simulate the amount of data submitted by 3k servers or more.

This is quite serious load. I'd say you may need to scale-up the cluster: one of our clusters handles a few thousand profiles per second and counts about a hundred of ingesters. As a general guidline, I'd suggest having at least 10 ingesters, 5 distributors, and 5 store-gateways per a 1k RPS (given the replication factor is 3).

Unfortunately, if the blocks have already been produced, there are not many ways to scale the read path. But you can try to parallelize the query over time intervals: [`-querier.split-queries-by-interval=15m`](https://grafana.com/docs/pyroscope/next/configure-server/reference-configuration-parameters/) might be helpful.

> Currently not, I was planning to extend the logging in block_querier.go's MergeProfilesStacktraces() to get that but any hints on how to point Jaeger (I guess) at the cluster would also be very appreciated. I looked into the Go opentracing package Pyroscope uses but it appear deprecated.

It would be very helpful if you provided us with CPU and memory heap in-use profiles collected from one of the ingesters during the query. Also, could you please post here `meta.json` file of one of the blocks?

**Comment by kolesnikovae** [comment]
One more thing I'd like to confirm with you – how EFS volume is mounted. Is it shared among instances?

> but any hints on how to point Jaeger (I guess) at the cluster would also be very appreciated. I looked into the Go opentracing package Pyroscope uses but it appear deprecated.

Regarding tracing: I'm sorry about docs, and thank you for pointing this out, we'll update them accordingly. Pyroscope expects the agent's host is specified via the `JAEGER_AGENT_HOST` env variable:

https://github.com/grafana/pyroscope/blob/8e158f44094cce241605a63e1717746080f967ed/pkg/phlare/phlare.go#L278-L285

**Comment by luisgerhorst** [comment]
> Unfortunately, if the blocks have already been produced, there are not many ways to scale the read path.

That's interesting, I was under the assumption that scaling would immediately affect the query runtime, even for data already in storage. I will scale the cluster to 10 ingesters now and report back. 

Now that I think about it this makes sense as I had 3h queries working (and 6h failing) with data submitted+queried while the cluster had 6 ingesters earlier. With that I already tried split-queries-by-interval=3h but it did not appear to help, I will try split-queries-by-interval=15min now.

> As a general guidline, I'd suggest having at least 10 ingesters, 5 distributors, and 5 store-gateways per a 1k RPS (given the replication factor is 3).

That's very helpful, thanks!

> It would be very helpful if you provided us with CPU and memory heap in-use profiles collected from one of the ingesters during the query.

WIP.

> Also, could you please post here meta.json file of one of the blocks?

Here you go: https://gist.github.com/luisgerhorst/dcb01083b06573c69a630ff7339f0d19#file-meta-json - That's from S3 because I can not easily access the EFS.

> One more thing I'd like to confirm with you – how EFS volume is mounted. Is it shared among instances?

It is shared among the instances. I was not sure about this earlier (especially about the shipper file) but isn't that what the default Helm chart suggests with `persistence: { enabled: true, existingClaim: my-efs-backed-data-pvc }`?

**Comment by kolesnikovae** [comment]
> Here you go: https://gist.github.com/luisgerhorst/dcb01083b06573c69a630ff7339f0d19#file-meta-json - That's from S3 because I can not easily access the EFS.

Thank you! That's interesting: the version you run should produce blocks in v3 format. Is it possible that this one was generated by another version? Apart from that I can say that the block is pretty small, just a million of profiles, so I expect no performance issues. 

> It is shared among the instances. I was not sure about this earlier (especially about the shipper file) but isn't that what the default Helm chart suggests with `persistence: { enabled: true, existingClaim: my-efs-backed-data-pvc }`?

I'm a bit concerned about the performance of EFS and I'm wondering if there are any performance degradation indicators in the AWS EFS dashboard. We're currently experimenting with optimizing how data is retrieved from disk and from S3, but even in the latest version, a query can cause massive I/O spikes. So if possible, I would ask you to try EBS volumes instead.

**Comment by luisgerhorst** [comment]
> That's interesting: the version you run should produce blocks in v3 format. Is it possible that this one was generated by another version

Ah, yes. Here's a more recent one: https://gist.github.com/luisgerhorst/1a51ed6b049f2a1961300ae5fbf19ee9

> I'm a bit concerned about the performance of EFS and I'm wondering if there are any performance degradation indicators in the AWS EFS dashboard.

At least according to the dashboard we are well below the limits (maximums below 1%).

> So if possible, I would ask you to try EBS volumes instead.

Unfortunately EBS is not available when using Fargate to run the pods. If the issue persists I can consider it but I would prefer not having to manage the nodes.

**Comment by luisgerhorst** [comment]
> I will scale the cluster to 10 ingesters now and report back (coincidentally I currently see 500 to 1k new TCP flows per second in my network infra).

I'm still getting a 503 with that setup when querying data for 6h or more. 3h sometimes works.

> Do you, by any chance, happen to have a profile from the ingester / store-gateway or maybe a trace of the query?

I have now set Jaeger up and I think only the top-level request to `/pyroscope/render` is failing with an HTTP error. I will send you the full trace to your GitHub commit mail as it is rather large (and I'm not sure if it contains any sensitive information).

This is only the trace. Do you think a CPU/memory profile is also required? I have not found a way to tell Pyroscope (deployed with the Helm chart) to scrape itself.

**Comment by kolesnikovae** [comment]
Thank you so much @luisgerhorst for the trace dump. I'll take a careful look today and get back to you shortly.

> Do you think a CPU/memory profile is also required? I have not found a way to tell Pyroscope (deployed with the Helm chart) to scrape itself.

I think the trace should be enough

**Comment by kolesnikovae** [comment]
There are a number of issues, I think:

1. Apparently, default values controlling query parallelism are overly conservative, therefore I suggest increasing them:
   - `-querier.max-concurrent=32`
   - `-query-frontend.scheduler-worker-concurrency=32`

Honestly, it might be hard to find the perfect balance, but the only reason these limits exist is to prevent OOM kills of queriers, ingesters, and store gateways.

Default values are:
```yaml
# The maximum number of concurrent queries allowed.
# CLI flag: -querier.max-concurrent
[max_concurrent: <int> | default = 4]

# Number of concurrent workers forwarding queries to single query-scheduler.
# CLI flag: -query-frontend.scheduler-worker-concurrency
[scheduler_worker_concurrency: <int> | default = 5]
```

2. Parquet pages are read extremely slowly both on ingesters and store-gateways, and it does not seem that the cause is IO latency (it is true for ingesters at least). In this specific span, little less than 90K profiles have been read and merged:
<img width="1662" alt="image" src="https://github.com/grafana/pyroscope/assets/12090599/96ce4f4a-125b-42f8-964f-04ddb48b0f6f">

This almost perfectly matches expected ingestion rate of 300 CPU profiles per second (4.5K profiled targets with the default 15s scrape interval).

As far as I can judge, you may need to scale up ingesters and storage gateways, because the bottleneck is CPU. I would double check this with a profile, or a system-wide metric :) I'll provide you with the detailed guide tomorrow as it is late in my time zone

**Comment by kolesnikovae** [comment]
> I have not found a way to tell Pyroscope (deployed with the Helm chart) to scrape itself.

We're currently working on the documentation therefore it might be misleading sometimes. I'm really sorry for the inconvenience.

I think, the simplest way to enable self-profiling with helm chart is as follows:

1. Make sure the image is up to date in `values.yaml` – I'm using the latest weekly build:
```yaml
# ...

  image:
    repository: grafana/pyroscope
    pullPolicy: IfNotPresent
    tag: weekly-f28-3d25aa29

# ... 

```
 2. Make sure `values.yaml` contains `config.scrape_config` – the default configuration includes k8s discovery that should allow pyroscope to find all the pods annotated with `phlare.grafana.com/scrape: "true"`, including its own ones.

https://github.com/grafana/pyroscope/blob/6212903d3ebc8ae51d9171f06a4cdbbd595b012f/operations/pyroscope/helm/pyroscope/values.yaml#L168-L188

 3. Apply changes:
```
helm upgrade --install {release_name} ./operations/pyroscope/helm/pyroscope --values ./operations/pyroscope/helm/pyroscope/values-micro-services.yaml
```

Contents of `./operations/pyroscope/helm/pyroscope/values-micro-services.yaml` in my case (I decreased `replicaCount` to run it on my laptop):
```yaml
pyroscope:
  components:
    querier:
      kind: Deployment
      replicaCount: 1
    query-frontend:
      kind: Deployment
      replicaCount: 1
    query-scheduler:
      kind: Deployment
      replicaCount: 1
    distributor:
      kind: Deployment
      replicaCount: 3
    agent:
      kind: Deployment
      replicaCount: 1
    ingester:
      kind: StatefulSet
      replicaCount: 3
    store-gateway:
      kind: StatefulSet
      replicaCount: 3
      persistence:
        enabled: false

minio:
  enabled: true
```

 4. For local tests it might be helpful to forward the frontend:
```
kubectl --namespace default port-forward svc/phlare-test-pyroscope-query-frontend 4040:4040
```

 5. If everything is okay, you should be able to see apps in the native UI via [http:/localhost:4040/ui]():

<img width="1656" alt="image" src="https://github.com/grafana/pyroscope/assets/12090599/9e378927-5434-4561-acad-62e6b475cd0b">

**Comment by luisgerhorst** [comment]
Sorry for the delay, I had to fix a few issues with our setup to ease debugging...

> 1. Apparently, default values controlling query parallelism are overly conservative, therefore I suggest increasing them: [...] 

> As far as I can judge, you may need to scale up ingesters and storage gateways, because the bottleneck is CPU.

I am now running a cluster with 20 ingesters (and 10 distributors/storage-gateways each) as well as `scheduler_worker_concurrency=32` and `max_concurrent=32`, but the issue persists. I will setup up the self-profiling and get back to you. Thanks for the detailed guide!

I can also scale up the cluster further, but needing approx. 1 ingester (+ respective amount of other nodes) per 200 clients seems to be quite excessive already. Especially if this will then only allow queries for 3h to work reliably.

**Comment by kolesnikovae** [comment]
No worries, and thanks for carrying out the experiment!

> I am now running a cluster with 20 ingesters (and 10 distributors/storage-gateways each) as well as scheduler_worker_concurrency=32 and max_concurrent=32, but the issue persists.

That's interesting. Could you please dump another trace? 

> I will set up up the self-profiling and get back to you. Thanks for the detailed guide!

The guide is a bit out of date: we released v1 this week 😅 I'd recommend to upgrade the cluster as we've changed the way self-profiling works; it is enabled by default, no additional configuration is required

**Comment by kolesnikovae** [comment]
Another problem is that there are only 3 targets, therefore only 3*(Replication Factor) ingesters are actually utilized.

Pyroscope distributes profiles across ingesters based on the _label set_ associated with the profile using a [hash-ring](https://grafana.com/docs/pyroscope/latest/reference-pyroscope-architecture/hash-ring/), and in your case each of three targets has only one label set, I guess. I think it may make sense to add some more targets (and adjust scrape config accordingly).

**Comment by luisgerhorst** [comment]
> Another problem is that there are only 3 targets, therefore only 3*(Replication Factor) ingesters are actually utilized.

Yikes, this actually seems to be the problem. After upgrading to 1.0.0 I see that only 3 ingester's CPU usage spikes when I do a query. I will test with more diverse tags (by adding a UUID and restarting the agents every couple minutes as I can not easily get that many client machines) and report back but this seems very promising.

**Comment by luisgerhorst** [comment]
I think that was a large part of the problem, however I am still getting the error when querying data for more than 2 days from 1.5k simulated clients (using 20 store gatways and 20 ingesters, scaling further did not resolve it). This should be 16x the data that worked in the beginning (3 hosts @ 100kHz x 1h vs. 1 host @ 100kHz x 48h), thus thanks a lot for the help so far!

I will try to dig into it myself a little but I have a few questions to which an answer would be extremely helpful:

- From the Jaeger traces it appears, as if one store-gateway takes > 30s to perform `mergeprofilesstacktraces`, does it make sense that this causes the render to fail? I assume this could again be due to too much data in one block, therefore I am planning to further diversify the tags I am submitting. Maybe it would also make sense to reduce the time per block?
- As each block contains traces from 3h, why does it make sense to set `split_queries_by_interval` to any value below that? Wouldn't that simply result in multiple requests being submitted to the same pod and therefore not reduce the total amount of time until these are server?
- Do I see it correctly that increasing `scheduler_worker_concurrency` and `max_concurrent` to any value larger than the number of nodes does not make sense?
- As the ingesters only have to search the last 4h, do I see it correctly that there is no need to increase their number unless I see pushes failing or that the query is bottlenecked by them doing `mergeprofilesstacktraces`? 
- When I increase the number of store-gateways, can I expect an immediate decrease in the query time?

**Comment by kolesnikovae** [comment]
> I think that was a large part of the problem, however I am still getting the error when querying data for more than 4 days

Exciting news, that's a very good progress! We're currently working on block compaction, which should reduce amount of data processed from the store-gateway significantly. The compactor will deduplicate data to compensate the replication factor for blocks uploaded to the object store.

--- 

> From the Jaeger traces it appears, as if one store-gateway takes > 30s to perform mergeprofilesstacktraces, does it make sense that this causes the render to fail?

Yes, `mergeprofilesstacktraces` is basically the job backend does to build the profile.

> I assume this could again be due to too much data in one block, therefore I am planning to further diversify the tags I am submitting. Maybe it would also make sense to reduce the time per block? 

> As each block contains traces from 3h, why does it make sense to set split_queries_by_interval to any value below that? Wouldn't that simply result in multiple requests being submitted to the same pod and therefore not reduce the total amount of time until these are serverd?

It solves multiple problems. The first stage of the query is finding relevant profiles in ingesters/store-gateways. Because of the replication factor, we need to deduplicate the data stream, which is a synchronous process very sensitive to IO latencies, but is not CPU-bound. Therefore we try to do it concurrently by deduplicating and processing smaller chunks independently. 

However, you're right that the value might be inappropriately low if you query days of data; increasing it to several hours may improve performance. I should say, that a static value here is not very useful, we should come up with a better heuristic.

> Do I see it correctly that increasing scheduler_worker_concurrency and max_concurrent to any value larger than the number of nodes does not make sense?

`max_concurrent` specifies how many queries (or sub-queries) a particular querier can handle simultaneously. We only need this limit to protect from OOMs. Ideally, queriers should have resource-aware throttling which we don't have yet.

As for ingesters and store-gateways (especially) I can say that here processing is mostly IO-bound, therefore we should try to run as many query in parallel as possible until we exhaust the memory available or the object storage throughput.

> As the ingesters only have to search the last 4h, do I see it correctly that there is no need to increase their number unless I see pushes failing or that the query is bottlenecked by them doing mergeprofilesstacktraces?

Correct.

> When I increase the number of store-gateways, can I expect an immediate decrease in the query time?

Yes, the improvement should be immediate.

**Comment by luisgerhorst** [comment]
Thanks a lot, this was very helpful. Closing this as the original issue has been fixed.
