### ISSUE TITLE
negative memory profiles 

### ISSUE THREAD

**Issue by korniltsev** [grafana/pyroscope#2282]
https://ops.grafana-ops.net/explore?panes=%7B%22xsC%22:%7B%22datasource%22:%22grafanacloud-profiles%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bservice_name%3D%5C%22profiles-prod-003%2Fdistributor%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:alloc_objects:count:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22grafanacloud-profiles%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

noticed we have negative memory profiles 

![Screenshot_20230821_104533](https://github.com/grafana/pyroscope/assets/331773/4eec24a6-5b9f-4a53-9dee-424983953446)

**Comment by kolesnikovae** [comment]
Also queries fail with panic: https://github.com/grafana/pyroscope/issues/2179

**Comment by korniltsev** [comment]
Yeah, this query gives me 503  very often https://ops.grafana-ops.net/explore?panes=%7B%22xsC%22:%7B%22datasource%22:%22grafanacloud-profiles%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bservice_name%3D%5C%22profiles-prod-003%2Fdistributor%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22grafanacloud-profiles%22%7D,%22maxNodes%22:10000%7D%5D,%22range%22:%7B%22from%22:%221692590514772%22,%22to%22:%221692590548098%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by kolesnikovae** [comment]
I can reproduce the problem with negative samples: 

```go
		s := new(Tree)
		s.InsertStack(-1, "foo", "bar")
		s.InsertStack(1, "foo", "bar", "baz")
		g := NewFlameGraph(s, -1)
		NewFlameGraphMerger().MergeFlameGraph(g)
```

Basically, if we get negative values, the resulting flamegraph is invalid, as the offset becomes negative:
https://github.com/grafana/pyroscope/blob/76e21bcf3a8d191bcce128cc72bf8a2317818e57/pkg/model/flamegraph.go#L72 

I'm not sure if we want to support negative values therefore for now I'm going to drop them: #2283

**Comment by kolesnikovae** [comment]
It's interesting, that it also causes symptoms like #2061 even with disabled tree truncation. My understanding is that this is happening because of the malformed `xOffset` – it does not always cause a panic actually, but may result in an "impossible" stack trace; and because the order in which we merge the intermediate flamegraphs is unpredictable, the structure of the resulting flamegraph is not stable
