### ISSUE TITLE
unrecognised module name: store-gateway

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/pyroscope#2302]
#### Describe the bug
Getting the below error in pyroscope-store-gateway pod. 
failed running phlare: unrecognised module name: store-gateway

#### To Reproduce

Start phlare in microservice mode with operations/pyroscope/helm/pyroscope/values-micro-services.yaml

#### Expected behavior

It should be up without any issues

#### Environment

- Infrastructure:Kubernetes
- Deployment tool: helm

![image](https://github.com/grafana/pyroscope/assets/15136443/c8dc408a-cdea-421f-8d42-0dbea70d1ec6)

**Comment by mvkrishna86** [comment]
@petethepig  and @simonswine can you please help?

**Comment by simonswine** [comment]
Do you mind sharing your values.yaml file and the version of the helm chart (e.g. in your `helm install` command?)

My suspicion is the docker image used is too old.

**Comment by mvkrishna86** [comment]
Here is my HelmRelease file I am using with kustomization and flux:


`apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pyroscope
  namespace: profiling
spec:
  interval: 1h0m0s
  releaseName: pyroscope
  serviceAccountName: devops
  timeout: 10m
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
  chart:
    spec:
      chart: pyroscope
      version: 0.5.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:

    # Default values for pyroscope.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    pyroscope:
      nodeSelector:
        workload: monitoring
      tolerations:
        - operator: Exists
      components:
        querier:
          kind: Deployment
          replicaCount: 3
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 256Mi
              cpu: 1
        query-frontend:
          kind: Deployment
          replicaCount: 2
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 256Mi
              cpu: 100m
        query-scheduler:
          kind: Deployment
          replicaCount: 2
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 256Mi
              cpu: 100m
        distributor:
          kind: Deployment
          replicaCount: 2
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 256Mi
              cpu: 500m
        agent:
          kind: Deployment
          replicaCount: 1
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 128Mi
              cpu: 50m
        ingester:
          kind: StatefulSet
          replicaCount: 1
          terminationGracePeriodSeconds: 600
          resources:
            limits:
              memory: 16Gi
            requests:
              memory: 8Gi
              cpu: 1
        store-gateway:
          kind: StatefulSet
          replicaCount: 1
          persistence:
          # The store-gateway needs not need persistent storage, but we still run it as a StatefulSet
          # This is to avoid having blocks of data being
            enabled: false
          resources:
            limits:
              memory: 16Gi
            requests:
              memory: 8Gi
              cpu: 1

    minio:
      enabled: true
      nodeSelector:
        workload: monitoring
      tolerations:
        - operator: Exists
  `

**Comment by cyriltovena** [comment]
The image by default in the chart doesn't support the store-gateway this was omitted by me.

```
☸ kind-pyroscope-dev in pyroscope on  feat/helm-grafana-agent [$!] via 🐹 v1.20.4 via  v20.3.0 on ☁️  cyril.tovena@grafana.com 
❯ docker run  grafana/phlare:0.5.1  -target="store-gateway"        
Unable to find image 'grafana/phlare:0.5.1' locally
0.5.1: Pulling from grafana/phlare
ca7dd9ec2225: Pull complete 
cd1044dda1ae: Pull complete 
bbc1631d7dac: Pull complete 
b4e75ff4160b: Pull complete 
334f1cb0e668: Pull complete 
1402e7c13013: Pull complete 
4ca8d95db52f: Pull complete 
Digest: sha256:330f990cdad942e7d6d3e0144494ea54c3ef65ac9e4b4fac3b9b4b556f0fe1c0
Status: Downloaded newer image for grafana/phlare:0.5.1
failed running phlare: unrecognised module name: store-gateway

☸ kind-pyroscope-dev in pyroscope on  feat/helm-grafana-agent [$!] via 🐹 v1.20.4 via  v20.3.0 on ☁️  cyril.tovena@grafana.com took 5s 
❯ docker run  grafana/phlare:0.6.1  -target="store-gateway"
Unable to find image 'grafana/phlare:0.6.1' locally
0.6.1: Pulling from grafana/phlare
f56be85fc22e: Already exists 
ca143f8388fd: Pull complete 
aacccb984de1: Pull complete 
6b291b70c250: Pull complete 
fd094a321c8b: Pull complete 
a2938f56c654: Pull complete 
c17391044eb7: Pull complete 
Digest: sha256:41a174499b4ec46e32c872aa5f6793de283d9b0194fd5e3ba3d9b75fff43da29
Status: Downloaded newer image for grafana/phlare:0.6.1
failed running phlare: error initialising module: storage: storage bucket configuration is required when running in microservices mode
```

If you want to keep using this chart change the image tag to 0.6.1.

You can also test our latest v1.0-RC https://artifacthub.io/packages/helm/grafana/pyroscope

```
helm repo add grafana https://grafana.github.io/helm-charts
curl -Lo values-micro-services.yaml https://raw.githubusercontent.com/grafana/pyroscope/next/operations/pyroscope/helm/pyroscope/values-micro-services.yaml
helm install pyroscope grafana/pyroscope --values values-micro-services.yaml
```

**Comment by mvkrishna86** [comment]
Thanks @cyriltovena. I started using 0.9.0. Now the issue is resolved.
Another issue I am facing is the minio jobs for creating the bucket and user are not having nodeSelector options. Not sure how we can fix from pyroscope end. But something to bother if we are using minio.

**Comment by cyriltovena** [comment]
Have you check the minio chart documentation https://github.com/minio/charts/blob/main/minio/values.yaml#L202 ?

**Comment by mvkrishna86** [comment]
> Have you check the minio chart documentation https://github.com/minio/charts/blob/main/minio/values.yaml#L202 ?

Yes @cyriltovena . But that is working only for the minio statefulset not for the Jobs.
