### ISSUE TITLE
Revive Pyroscope remote-write

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#2370]
We used to have a remote-write feature for pyroscope that was very convenient for managing profiling data and where to send it. We had to remove this functionality in Pyroscope 1.0, but have a request in slack to bring it back:

https://pyroscope.io/docs/remote-write/

![173495597-ecbe1f83-174b-4fa5-80b5-7b3d55b08672](https://github.com/grafana/pyroscope/assets/23323466/da538621-f13e-4bf3-9fbd-226d8a1ec784)

**Comment by Rperry2174** [comment]
after discussing the Grafana agent is best way to achieve same goal so likely will not bring this back

**Comment by Neal** [comment]
> We used to have a remote-write feature for pyroscope that was very convenient for managing profiling data and where to send it.

Agreed and would be great to not require Grafana agent as we prefer application side control on when to send data to Pyroscope.

@Rperry2174 any chance to revisit this?

**Comment by juangom** [comment]
We also require the remote-write feature. For now I think we'll use pre v1 in the the local server to write to a remote one.
