### ISSUE TITLE
Add "color by" dropdown

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#24]
Currently we determine a nodes color based off of the file it came from. As we start to add more metrics to this page, we may want to start coloring nodes off of other things. Some examples include:
- a monochrome color that varies in intensity/brightness based off of self time
- a monochrome color that varies in intensity/brightness based off of total time
- coloring for libraries vs user code (i.e. pandas or numpy would be a different color than code someone wrote)

And while this wouldn't be part of the dropdown, worth noting that eventually we hope to add:
- coloring for a diff

While we aren't looking to implement all of these at once, just having the ability to switch [coloring methods](https://github.com/pyroscope-io/pyroscope/blob/1a9e65467c22377c311836195d02f9a772e1b486/webapp/javascript/util/color.js#L33-L38) based off a dropdown is the first step.

**Comment by petethepig** [comment]
As discussed in #657 we should also consider how friendly this is for colorblind users. 

rough todo on that front:

* [ ] review existing colors
* [ ] for the diff, look into tweaking the existing red / green colors to be more distinguishable
* [ ] for the diff, add other options outside of just red / green

some materials I found so far:
* https://www.tableau.com/about/blog/examining-data-viz-rules-dont-use-red-green-together
