### ISSUE TITLE
Explore memory profiling in .NET

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#241]
We recently added support for .net profiling (#117). We should start doing the research needed to add memory profiling for .net.

**Comment by nicolastakashi** [comment]
Hey Peeps!
Just to share that it would be nice, and I would love to help in some manner way

dotnet is highly adopted in enterprise companies and has a tool that makes it easy, without a doubt will help the enterprise landscape that is using dotnet adopt Pyroscope 🤟🏼

**Comment by extesy** [comment]
Adding my vote. Working in medium-sized public company using C# and runtime memory profiling would be very beneficial.

**Comment by dauchande** [comment]
Has there been any research done into Microsoft's pprof variant dotnet-monitor as an option?  https://github.com/dotnet/dotnet-monitor

**Comment by Rperry2174** [comment]
closing this as we now support memory profiling -- will continue discussion about dotnet-monitor in https://github.com/grafana/pyroscope/issues/2369
