### ISSUE TITLE
Default to "color by package" 

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#2463]
Right now there are two options 
![image](https://github.com/grafana/pyroscope/assets/23323466/929cec18-655a-4a4c-baf8-392698b60985)
- "color by value"
-  "color by package"

we discussed this and we would like to default (both in grafana and in our app plugin) to defaulting to "color by package" instead of "color by value"

**Comment by aocenas** [comment]
Implemented in the package here https://github.com/grafana/grafana/pull/76137

**Comment by aocenas** [comment]
Fixed by https://github.com/grafana/pyroscope/pull/2509
