### ISSUE TITLE
Simplify UI elements related to profile types

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#2492]
<img width="1393" alt="image" src="https://github.com/grafana/pyroscope/assets/23323466/3daecd81-79b8-4d8d-9ca4-d98014ca4e09">

The text that we show to users related to sample types is kind of confusing and we should simplify this on the frontend. 

1. We should remove the `process_cpu` (non-bolded part) from being _displayed_ in the dropdown
- in the case of `process_cpu: cpu` it is redundant
- in the case of `process_cpu: alloc_objects` that is just how we store it on the backend, but to a user that is incorrect 

instead it should just be 
- `cpu`
- `alloc_objects`

3. We should remove the long text string from the query box 
Note that this is still needed on the backend, but we should show users something much more simple (i.e. just a un-clickable button) 

![image](https://github.com/grafana/pyroscope/assets/23323466/08aa8b27-d85f-4081-883b-48bb17c400a0)

**Comment by grafakus** [comment]
@Rperry2174 Just to be sure, may I ask you to confirm what is expected? Are these assumptions correct:

1. Remove **only** the "process_cpu: " prefix from the label of each "Profile" dropdown item - this means that (e. g.) "memory: ", "goroutine: " prefix are not removed.
2. To be consistent, the text highlighted in red on your screenshot should have the same rule applied.
3. The text highlighted in red on your screenshot should be removed from the query box but still visible. The user should not be able to modify it, they should only be able to modify the `{service_name="pyroscope"}` part.

?

**Comment by Rperry2174** [comment]
good question... let me clarify 

1. in the dropdown the prefix should be removed _entirely_ no matter what the profile type the dropdown should only show the bolded section. Reasoning is that the bolded section will always just resay what the non-bolded section is anyway. 
2. the red part will only have **one** element which will show users what the profile type is. The red part should be replaced with a static button (outside of the text box) via the following table:


process_cpu:cpu:nanoseconds:cpu:nanoseconds -> cpu
memory:alloc_objects:count:space:bytes -> memory
process_cpu:alloc_samples:count:cpu:nanoseconds -> memory
process_cpu:alloc_size:bytes:cpu:nanoseconds -> memory
process_cpu:exception:count:cpu:nanoseconds -> exceptions
process_cpu:lock_count:count:cpu:nanoseconds -> locks
process_cpu:lock_time:nanoseconds:cpu:nanoseconds -> locks
memory:alloc_in_new_tlab_bytes:bytes:: -> memory
memory:alloc_in_new_tlab_objects:count:: -> memory

Note: I may be missing a few profile types specifically for java -- i will check, but in the mean time we need a default for things not listed in this table 

I added a green square to show what that should look like 

3. The text highlighted in red on your screenshot should be removed from the query box but still visible. The user should not be able to modify it, they should only be able to modify the {service_name="pyroscope"} part. **Correct.**

**Comment by Rperry2174** [comment]
in fact, let's also add an (i) icon:
![image](https://github.com/grafana/pyroscope/assets/23323466/57cdba9b-c5b6-46cc-bcae-6eaa6d369f26)

this will allow for when users hover over the profile type we can provide a description of what that profile type means:
```
const profilingMetrics = {
    "process_cpu:cpu:nanoseconds:cpu:nanoseconds": {
        type: "cpu",
        description: "Measures the CPU processing time in nanoseconds."
    },
    "memory:alloc_objects:count:space:bytes": {
        type: "memory",
        description: "Counts the number of objects allocated in memory, represented in bytes."
    },
    "process_cpu:alloc_samples:count:cpu:nanoseconds": {
        type: "memory",
        description: "Samples the memory allocations over a duration of CPU time."
    },
    "process_cpu:alloc_size:bytes:cpu:nanoseconds": {
        type: "memory",
        description: "Size of memory allocations during a specific CPU processing time."
    },
    "process_cpu:exception:count:cpu:nanoseconds": {
        type: "exceptions",
        description: "Counts the number of runtime exceptions during the CPU processing time."
    },
    "process_cpu:lock_count:count:cpu:nanoseconds": {
        type: "locks",
        description: "Measures the number of times a process attempted to acquire a lock during CPU processing time."
    },
    "process_cpu:lock_time:nanoseconds:cpu:nanoseconds": {
        type: "locks",
        description: "Time spent waiting for a lock to become available during CPU processing."
    },
    "memory:alloc_in_new_tlab_bytes:bytes::": {
        type: "memory",
        description: "Bytes allocated in a new Thread-Local Allocation Buffer (TLAB)."
    },
    "memory:alloc_in_new_tlab_objects:count::": {
        type: "memory",
        description: "Count of objects allocated in a new Thread-Local Allocation Buffer (TLAB)."
    }
};

console.log(profilingMetrics);

```

**Comment by darrenjaneczek** [comment]
This issue is mostly in the pyroscope app plugin. Do we want to move this issue to that repo?
Also, do we want to make this shortened "CPU (i)" symbolic block appear in the query the oss-pyroscope webapp?
I can see this being a nice `QueryInput` override exclusive to the app plugin, where we can also make that implementation use more platform native components.
