### ISSUE TITLE
Helm-Chart fails with NodePort type

### ISSUE THREAD

**Issue by ascknx** [grafana/pyroscope#2634]
#### Describe the bug
When deploying the Helm Chart with NodePort service type set it will fail because of the hardcoded `clusterIP: None`:

```
Service "pyroscope-headless" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for NodePort services
```

#### To Reproduce

Set pyroscope.service.type=NodePort

**Comment by kolesnikovae** [comment]
Should be fixed by https://github.com/grafana/pyroscope/pull/2699
