### ISSUE TITLE
Find a way to partition segment trees

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#264]
### Problem

If you insert 1 year of profiling data that will generate 3,504,000 segment tree nodes. It's not bad per se, but it creates this problem where serialization / deserialization of these trees now takes up a lot of time.

![Screen Shot 2021-06-25 at 10 36 40 AM](https://user-images.githubusercontent.com/662636/123464088-3c1e4600-d5a1-11eb-9e53-5de291dbb1b9.png)

#### Step 1. Optimize serialization

This is the easy part. Currently we're using [varints](https://developers.google.com/protocol-buffers/docs/encoding#varints) to encode 6 numbers:
```
depth    int
time     time.Time
present  bool
samples  uint64
writes   uint64
length of children array
```

[Varints](https://developers.google.com/protocol-buffers/docs/encoding#varints) are great but are an overkill for most of these:

* `depth    int` — 3 bits for this (16 levels) should be more than enough I think

![Screen Shot 2021-06-25 at 10 36 04 AM](https://user-images.githubusercontent.com/662636/123464055-2dd02a00-d5a1-11eb-9723-77977aace065.png)

* `time     time.Time` — we don't really need to store time (that takes 4-5 bytes per node). time can be stored once per segment tree and then calculated for each segment tree node. we might have to store index in children array instead, but that's also not gonna take up more than 3 bits
* `present  bool` — boolean always takes a bit, so this one is simple
* `samples  uint64` — this to me seems like the only value that truly needs a varint
* `writes   uint64` — this one needs a varint. We could take advantage of the fact that this value is only used for some types of profiles. And so maybe we could skip this field in cases where it doesn't make a difference
* `length of children array` — this won't be higher than 10, so another 3 bits.

^ based on this it seems like we could pack 4 of these into 2 bytes, skipping the varint logic altogether.

#### Step 2. Partition Segment Trees

This is a bit more complex. Basically, the idea I have is that we split the segment tree into multiple chunks. We could have a wrapper object that would make it look like this is all one big tree for users.

![Page2 11](https://user-images.githubusercontent.com/662636/123466674-763d1700-d5a4-11eb-8aa1-777eb89be34c.png)

The biggest question I have for this right now is where do we start splitting the trees? Here's some napkin math:

![Screen Shot 2021-06-25 at 11 11 36 AM](https://user-images.githubusercontent.com/662636/123468322-73dbbc80-d5a6-11eb-9927-4b5a5642ca82.png)

The coloring is not very scientific and mostly just based on intuition.

Here's a link to the spreadsheet: https://docs.google.com/spreadsheets/d/17-DjbAUxLhmh_wdrx0PQ9CiBG544qBOkXef8v7UvNmQ/edit?usp=sharing

**Comment by kolesnikovae** [comment]
To my understanding, during writing the data to a segment, we need only the last node for every level. I'm wondering could the level 3 be a good choice for us.
