### ISSUE TITLE
[DOC] Extend profilecli docs

### ISSUE THREAD

**Issue by aleks-p** [grafana/pyroscope#2650]
_Originally posted by @Rperry2174 in https://github.com/grafana/pyroscope/issues/2645#issuecomment-1795717619_

I have a few suggestions that could help improve the clarity and usability of the docs for users across different platforms.

### Installation Instructions:
Could you clarify the installation steps for profile-cli? It would be beneficial to include explicit instructions on how users can install this utility on their system.
- For macOS users, is it `brew install pyroscope-io/brew/pyroscope` or brew `install pyroscope-io/brew/profile-cli` or both?
- For Linux users or non-macOS CI pipelines, could you provide the equivalent installation commands?

Adding a section that walks through the installation process before diving into the usage would be helpful.

### Working Example:
A working example is always helpful as well. Could you add a complete, executable example to the [examples/api folder](https://github.com/grafana/pyroscope/tree/main/examples/api) on GitHub? This would give users a quick way to see profile-cli in action.

### Separate Installation Documentation:
The installation instructions might be better suited for a separate page. While this could be a subsequent improvement, let's ensure that the current document is as complete and stand-alone as possible. We can later refactor the content into separate, more detailed page

The goal is to make the documentation intuitive enough so that when users ask "How do I install/use profile-cli?", they can be directed to both the docs and a comprehensive guide that works for their specific setup without additional explanations

**Comment by knylander-grafana** [comment]
@aleks-p Do you think this issue is finished? You've done some great work towards it!

**Comment by aleks-p** [comment]
Yeah, closing as completed. Thank you for following up!
