### ISSUE TITLE
Data retention policies

### ISSUE THREAD

**Issue by Moreez317** [grafana/pyroscope#2671]
Hello! Previously (before version 1.0.0) Pyrscope had clear storage settings. It was something like:
```
retention levels:
    0: 6h
    1: 12h
    2: 48h 
```
Currently (in Pyrscope versions >= 1.0.0) the retention policy is very difficult to explain (or there is very little information about it in the documentation). I really can't set it up with S3 storage. How can this be customized and do you have any plans to improve it?

I'm really sorry for asking this question in GitHub issue.

**Comment by cyriltovena** [comment]
This retention is gone for now. 

You'll have to use the compactor now to achieve this we have a new config in 1.2 e.g `-compactor.blocks-retention-period=15d`. 

However currently the compactor doesn't run in a single binary more you'll have to use microservices deployment. Step 3 on this page explains how https://grafana.com/docs/pyroscope/latest/deploy-kubernetes/helm/

**Comment by Moreez317** [comment]
Thank you, helps a lot! That's what I was looking for and could't find in version 1.1.

**Comment by Moreez317** [comment]
Thank you, helps a lot! That's what I was looking for and could't find in version 1.1.

**Comment by vainikkaj** [comment]
> However currently the compactor doesn't run in a single binary more you'll have to use microservices deployment. Step 3 on this page explains how https://grafana.com/docs/pyroscope/latest/deploy-kubernetes/helm/

@cyriltovena Are there any plans for adding retention configuration into single binary deployments?
