### ISSUE TITLE
Error when we query data for more than 3 hours in grafana - "too many unhealthy instances in the ring"

### ISSUE THREAD

**Issue by Raghav65** [grafana/pyroscope#2710]
We've configured Pyroscope to use Azure Blob Storage bucket for long term storage, by setting the following configuration.

[pyroscope-config.txt](https://github.com/grafana/pyroscope/files/13380620/pyroscope-config.txt)

We are running Pyroscope in microservice mode. All pods (distributor, ingester, store gateway, querier, query scheduler and query frontend) are running. Data is getting flushed to azure storage but when we query data in grafana for more than 3 hours we are getting error "internal: too many unhealthy instances in the ring" and data is not loading.

Observation:
When we query and load data for last 6 hours in grafana explorer we are getting error "internal: too many unhealthy instances in the ring". 

We could see below logs in ingester when we query data more than 3 hours

ts=xxxxxx caller=http.go: level=warn traceID=xxxxxx orgID=xxxxxx msg="POST /ingester.v1.IngesterService/MergeProfilesLabels xx ms, error: 2 errors: http2: stream closed; http2: stream closed ws: false; ----------------------------------------------------------------------

We could see below logs in querier  when we query data more than 3 hours

ts=xxxxxx caller=http.go: level=warn traceID=xxxxxx orgID=xxxxxx msg="POST /querier.v1.QuerierService/SelectSeries (500) xx µs Response: \"{\\\"code\\\":\\\"unknown\\\",\\\"message\\\":\\\"read message: stream error: stream ID 5; NO_ERROR\\\"}\" ws: false; ----

We have set query_store_after to 4h in querier config and max_block_duration to 3h under pyroscopedb.

- Configure Pyroscope's Config Map to use an Azure Storage Account with Name/Key, Container Name and endpoint_suffix
- Start Pyroscope Pod in AKS
- Push profiles from sample application to Pyroscope's distributor endpoint
- Query data in grafana using Pyroscope's querier endpoint for more than 3 hours

Expected behavior
Pyroscope should connect to the Azure Blob Storage account and retrieve data for more than 3 hours. 

Environment

Infrastructure: Kubernetes (AKS)
Deployment tool: Helm

**Comment by simonswine** [comment]
This is a bug that I recently discovered and is fixed by #2706, so the release v1.2.0 should work in this setup.

I think you hitting this bug, because the replication factor for store-gateways is 3 and you are having less than 3 store-gateways, am I right?

**Comment by Raghav65** [comment]
> This is a bug that I recently discovered and is fixed by #2706, so the release v1.2.0 should work in this setup.
> 
> I think you hitting this bug, because the replication factor for store-gateways is 3 and you are having less than 3 store-gateways, am I right?

yeah I'm having only 1 store-gateway. I will keep 3 store-gateways and try if we are getting the same error.

**Comment by cyriltovena** [comment]
@Raghav65 let us know if we need to re-open this.
