### ISSUE TITLE
Using helm 1.2.0, but pyroscope 1.1.5 is used

### ISSUE THREAD

**Issue by be-hase** [grafana/pyroscope#2725]
It seems to be because the fixes to pyroscope 1.2.0 were made after helm 1.2.0 was released.
We can workaround by specifying `pyroscope.image.tag`, but I would be happy if the modified helm is released.

https://github.com/grafana/pyroscope/commits/main/operations/pyroscope/helm

![image](https://github.com/grafana/pyroscope/assets/903482/4184c860-7100-4a7d-bf2b-bef3e8dd1428)

**Comment by cyriltovena** [comment]
Thanks for the report. It needs another bump. Will do asap.

**Comment by be-hase** [comment]
thanks :)
