### ISSUE TITLE
[DOC] Add a new page that explains profile types 

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/pyroscope#2737]
Create a new page that describes the profile types and their usage, include examples of each profile type.

**Comment by Rperry2174** [comment]
Need to explain that fgprof is off-cpu profiling:

https://raintank-corp.slack.com/archives/C03NCLB4GG7/p1700657746738799

**Comment by Rperry2174** [comment]
https://gist.github.com/Rperry2174/e6b337eb9a6d81e26671b5ad16d7aa4f

**Comment by knylander-grafana** [comment]
Content added here: https://grafana.com/docs/pyroscope/next/ingest-and-analyze-profile-data/profiling-types/ 
Contributed by @Rperry2174  and structured in #2839

**Comment by knylander-grafana** [comment]
> Need to explain that fgprof is off-cpu profiling:
> 
> https://raintank-corp.slack.com/archives/C03NCLB4GG7/p1700657746738799

Do we want to include this topic in the initial doc or create another one to add that content?
