### ISSUE TITLE
Make Max Nodes parameter configurable in the built-in UI

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/pyroscope#2745]
We support this option in the Explore view and in the app plugin but not in the built-in UI.

At the moment there are two ways to override the limit:
1. By adding `maxNodes` parameter into the URL:
```
http://<host>/?query=<query>&from=now-1h&maxNodes=16384
```

2. By configuring the limit on the server side:
```yaml
  # Maximum number of flamegraph nodes by default. 0 to disable.
  # CLI flag: -querier.max-flamegraph-nodes-default
  [max_flamegraph_nodes_default: <int> | default = 8192]

  # Maximum number of flamegraph nodes allowed. 0 to disable.
  # CLI flag: -querier.max-flamegraph-nodes-max
  [max_flamegraph_nodes_max: <int> | default = 0]
```

**Comment by grafakus** [comment]
@kolesnikovae It seems we could close this issue, right?

**Comment by kolesnikovae** [comment]
Yep, I think it is irrelevant anymore

**Comment by DanielShaulov** [comment]
Hi @grafakus @kolesnikovae - I recently ran into this issue (fragmented graph and a large "other" section), and I didn't find any way to increase the `maxNodes` in the UI besides appending `&maxNodes=500000` to the url.
Am I missing some obvious button that was added? Or is the built-in UI just less maintained and I should be moving to Grafana UI?

**Comment by korniltsev** [comment]
The builtin UI is not maintained. grafana's explore or profiles drilldown is the way to go
