### ISSUE TITLE
Request for eBPF Source Code

### ISSUE THREAD

**Issue by GorilaMond** [grafana/pyroscope#2755]
Could give me the source code of ebpf/pyrobpf/profile_bpfel_x86.o? I want to try to expend the ability of eBPF part.

**Comment by korniltsev** [comment]
https://github.com/grafana/pyroscope/tree/main/ebpf/bpf

**Comment by GorilaMond** [comment]
> https://github.com/grafana/pyroscope/tree/main/ebpf/bpf

OK, thanks.
