### ISSUE TITLE
failed creating pyroscope: compactor block range periods should be divisible by the max block duration, but 1h0m0s is not divisible by 3h0m0s

### ISSUE THREAD

**Issue by Raghav65** [grafana/pyroscope#2768]
### Discussed in https://github.com/grafana/pyroscope/discussions/2764

<div type='discussions-op-text'>

<sup>Originally posted by **Raghav65** November 27, 2023</sup>
I'm using grafana/pyroscope version v1.2.0

I have configured compactor block_ranges as default and I'm getting below error message as by default block_ranges: <list of durations> | = 1h0m0s,2h0m0s,8h0m0s. 

failed creating pyroscope: compactor block range periods should be divisible by the max block duration, but 1h0m0s is not divisible by 3h0m0s

When I try to add below compactor config in compactor block in config.yaml I'm getting - " failed parsing config: /etc/pyroscope/config.yaml: yaml: unmarshal errors:   line x: cannot unmarshal !!str `3h0m0s` into compactor.DurationList"

  -compactor.block-ranges value
    	List of compaction time ranges. (default 3h0m0s,6h0m0s,12h0m0s)

    compactor:
        block_ranges: 3h0m0s

max_block_duration is set to 3h0m0s</div>

**Comment by cyriltovena** [comment]
So you do need your compactor to use 3h block ranges since that's your current max block duration. If you running a large cluster I suggest you switch to our default 1h.

Now for your error:

```
compactor:
    block_ranges: [3h0m0s]
```

Add `[]` like if it was an array. Sorry for the confusion.

**Comment by cyriltovena** [comment]
Let me know if you need more help

**Comment by Raghav65** [comment]
Thanks @cyriltovena It worked.
