### ISSUE TITLE
[DOC] Update the Grafana Agent > Go (pull) doc

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/pyroscope#2773]
Update this page: https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/go_pull/

Related: https://github.com/grafana/pyroscope/issues/2774 (eBPF doc update)

**Introduction**
This page needs a bit more of an introduction. This information could come from the [Grafana Agent page](https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/) section for Golang profiling. You could use almost all of this as the intro to the Go (pull) page: 

> In pull mode, the Grafana Agent periodically retrieves profiles from Golang applications, specifically targeting the pprof endpoints.
> 
> Benefits of Golang Profiling in Pull Mode:
> 
> Non-Intrusive: No need to modify your application’s source code.
> Centralized Profiling: Suitable for environments with multiple Golang applications or microservices.
> Automatic: The agent handles the pulling and sending of profiles, requiring minimal configuration.
> How to Set Up Golang Profiling in Pull Mode:
> 
> Ensure your Golang application exposes pprof endpoints.
> Install and configure the Grafana Agent on the same machine or container where your application runs.
> Ensure the agent is set to pull mode and targeting the correct pprof endpoints. For step-by-step instructions, visit the [Go (Pull Mode)](https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/go_pull) docs.
> The agent will start querying the pprof endpoints of your Golang application, collecting the profiles, and forwarding them to the Pyroscope server.  

If we move the equivalent information for the eBPF section from the Agent page to the eBPF page, then we'd rework the Agent page to remove duplicate content and simplify the information. (In other words, on the Ageht page we'd say "You can use the Agent with Golang or eBPF (summary) and then link to the subpages.)

What is the user journey for this page? To  configure Go in pull mode with Grafana Agent. If that is the case, then the focus of the information should be in support of that goal. 

In general, the current content needs to be restructured to help the user complete the steps. In it's current state, it's unclear 

### General suggestions: 

- Separate the reference material from the tasks by moving the Agent Configuration and Profiling Configuration sections to the bottom of the page. They can be referenced during the procedure. 
- Keep headings and content scannable so someone can find what they are looking for. 
- Provide a summary of the steps and then match the content structure to those steps.
- Consider renaming Prerequisites to "Before you begin".
- Use sentence case in headings (i.e., "Add profiling to the Grafana Agent" instead of title case and a gerund (-ing on a verb).

### Restructure based around task summary

Move or copy this entire section from the Agent page to the introduction: 

How to Set Up Golang Profiling in Pull Mode:

1. Ensure your Golang application exposes pprof endpoints.
2. Install and configure the Grafana Agent on the same machine or container where your application runs.
3. Ensure the agent is set to pull mode and targeting the correct pprof endpoints. For step-by-step instructions, visit the [Go (Pull Mode)](https://grafana.com/docs/pyroscope/next/configure-client/grafana-agent/go_pull) docs.
4. The agent will start querying the pprof endpoints of your Golang application, collecting the profiles, and forwarding them to the Pyroscope server.
5. Verify that configuration works

Each numbered item above becomes a heading with an explanation about how you complete (or test) each one of those tasks. Keep in mind that you may have to rework some of these items. 

Example page that uses this kind of structure https://grafana.com/docs/tempo/latest/setup/tanka/ 

Your "Example" section and the Add profiling to Grafana Agent have the beginnings of tasks, as does the Agent configuration. Consider removing the "Agent configuration" heading since the text underneath it describes how to add profiling to the Agent. "Agent Configuration" isn't needed. 

After reading the page, it seems like the Adding profiling to Grafana Agent should be followed by the Example section (retitled and rewritten as a task), and then the Profiling Configuration included underneath that as a reference section. 

(corresponds to step 3 above) Consider adding a section to validate the configuration. This can be as simple as pointing to other doc with an explanation that updates the specifics for profiling highlighted. You should include information on how to know it's successful. 

(corresponds to step 4) How can someone tell the profiling information is being recieved as expected? 

### Other topics

* Add deltadiff explanation and instructions
* Make the "agent documentation" a link to the correct page in this sentence:  "While this documentation will contain a simple example for more configuration options visit the agent documentation for [pyrosope.scrape](https://grafana.com/docs/agent/next/flow/reference/components/pyroscope.scrape/) and [pyroscope.write](https://grafana.com/docs/agent/next/flow/reference/components/pyroscope.write/#pyroscopewrite)."
* Consider moving the sentence, "Visit the [Pyroscope examples](https://github.com/grafana/pyroscope/tree/main/examples/grafana-agent) to see an example of how to run Pyroscope with the Grafana Agent." higher up in the page, maybe under the Example section. Seeing examples can be very helpful instead of getting lost in a configuration page.

**Comment by knylander-grafana** [comment]
Related: https://github.com/grafana/pyroscope/issues/2774

**Comment by korniltsev** [comment]
There is quite a lot of duplication between this page and component flow reference documentation

https://grafana.com/docs/agent/latest/flow/reference/components/pyroscope.write/


I personally "go_pull" page should not include this information and just have links to grafana agent docs.

However someone may say it is better to not leave the page and have everything available here at "go_pull" .

 If we include agent flow reference docs in  go_pull docs, we need to find a way to make it reusable, so that there is a single source of truth for agent flow docs.

**Comment by korniltsev** [comment]
>Add deltadiff explanation and instructions

I think it is better not explain it, but just provide instructions, enabling it by default, maybe one link to. Maybe just a link to readme.md or godoc. Users of godeltaprof dont really need to understand it in depth.

**Comment by knylander-grafana** [comment]
> There is quite a lot of duplication between go_pull page and component flow reference documentation
> 
> https://grafana.com/docs/agent/latest/flow/reference/components/pyroscope.write/
> 
> I personally "go_pull" page should not include this information and just have links to grafana agent docs.
> 
> However someone may say it is better to not leave the page and have everything available here at "go_pull" .
> 
> If we include agent flow reference docs in go_pull docs, we need to find a way to make it reusable, so that there is a single source of truth for agent flow docs.

Agreed that we don't want to have duplicate content and only have the information live in one file. We can share content between repositories [using shared files](https://grafana.com/docs/writers-toolkit/write/reuse-content/). Shared content can be a few paragraphs to multiple files from a directory. However, we want to be judicious in what we share across repositories because it adds other complications. 

Is there a balance for this content? For example, only give the minimum or most commonly used options and then link back to the reference doc?  In some cases, going back and forth between docs is unavoidable in the short term. We can revisit this and determine what content would be best to share.
