### ISSUE TITLE
[DOC] Update the Agent > eBPF doc

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/pyroscope#2774]
Like the Go (pull mode), this page has a lot of information but lacks a clear process for someone to complete the task of configuring the Agent to use eBPF.

Resource: https://pyroscope.io/blog/ebpf-profiling-pros-cons/ 

It seems like this page should be potentially divided multiple  pages - 

1. The tasks for setting up eBPF and profiling
2. The configuration reference (basically, from configuration to the troubleshooting section)
3. Troubleshooting 

As with the  Go (pull mode) notes, consider restructuring the content to match your summary steps from the Agent page: 

How to Set Up eBPF Profiling with the Grafana Agent:

1. Ensure your system runs a Linux kernel version 4.9 or newer. 
2. Install the Grafana Agent on the target machine or container.
3. Configure the agent to use eBPF for profiling. Refer to the [eBPF documentation](https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/ebpf) for detailed steps.
4. Once configured, the agent will start collecting eBPF profiles and send them to the Pyroscope server.
5. Verify that your configuration works

#1 is listed in the "Before you begin" Prereq section, so probably isn't an actual step, unless you include a section with instructions for verifying the Linux version. 

If you use the summary steps to match your headings, then you'll need to revisit the wording and structure of the content. You do have a procedure in this doc that just needs to be refined and fleshed out. 

As with other pages, consider moving the examples information up to where your tasks are so users can look at the examples. 

Introduction section - For the opening section, do you really need the first three headings? Here's what it could look like: 

**eBPF**
eBPF is an emerging Linux kernel technology that allows for user-supplied programs to run inside of the kernel. This enables a bunch of interesting use cases, particularly efficient CPU profiling of the whole Linux system.

The blog post “[The pros and cons of eBPF profiling](https://pyroscope.io/blog/ebpf-profiling-pros-cons)”   explores the benefits and tradeoffs of using eBPF and provides some examples of eBPF profiles. 

We recommend a hybrid approach for better results: eBPF to profile the node and specific language instrumentation per application. 

To set up eBPF profiling with the Grafana Agent, you need to: 

- Install the Grafana Agent on the target machine or container.
- Configure the agent to use eBPF for profiling. Refer to the [eBPF documentation](https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/ebpf) for detailed steps.
- Once configured, the Agent will start collecting eBPF profiles and send them to the Pyroscope server.

**Before you begin**
For the eBPF integration to work, you’ll need:

A Pyroscope server where the agent will send profiling data
A Linux machine with the kernel version >= 4.9 (due to [BPF_PROG_TYPE_PERF_EVENT](https://lkml.org/lkml/2016/9/1/831))

**Install the Grafana Agent**

...

**Configure eBPF for profiling**

...

**Verify profiles are received by the Pyroscope server**

...

**Comment by cyriltovena** [comment]
Ading a notes here that we don't talk about labels discovery and service name but we should.
