### ISSUE TITLE
Optimize language detection

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/pyroscope#2777]
We're currently using a set of regular expressions to derive the source code language based on the string table. This works well but the overhead might be quite substantial:

<img width="751" alt="image" src="https://github.com/grafana/pyroscope/assets/12090599/223e1170-6da0-489b-8678-28c06dbf3ef4">

We should probably consider optimizing the procedure. Some ideas:
 - Sampling: it makes little sense to inspect the whole table. I assume that sampling 5-15% of strings should be sufficient.
 - Short cuts: in most cases we can confidently determine the language based on the file extensions. We should probably try this first (without regexes, just suffix matching).
 - Skip the procedure if we can get this info from labels (spy_name).

Nevertheless, we should update all our SDKs to send some meta (such as language, version, platform, etc)

**Comment by cyriltovena** [comment]
We actually don't need SDK to do this. 

@aleks-p Recently added this into our `usagestats`, the same discovery process could be used at ingest time.

The big question though is how store and introduce it in the API ?

We could store it in tsdb (using a hidden labels) or in parquet.

For pprof API we can use sample labels, but not sure for the `SelectMergeStacktraces` API

**Comment by aleks-p** [comment]
@cyriltovena perhaps you misunderstood, this issue is primarily about optimizing the work done for the usage stats, as it looks like it is using quite a bit of cpu right now. Sampling, substring matching and skipping altogether if we can are all good ways to do this.

**Comment by aleks-p** [comment]
Regexp:
```
go.cpu.labels.pprof-10         	  330040	     10853 ns/op
heap-10                        	  195819	     18407 ns/op
dotnet.labels.pprof-10         	  143966	     24949 ns/op
profile_java-10                	   61840	     58016 ns/op
profile_nodejs-10              	  109437	     32871 ns/op
profile_python-10              	  391418	      9156 ns/op
profile_ruby-10                	  307896	     11783 ns/op
profile_rust-10                	  636633	      5668 ns/op
```

String matching (prefix or suffix):
```
go.cpu.labels.pprof-10         	 3418387	      1060 ns/op
heap-10                        	 2446440	      1483 ns/op
dotnet.labels.pprof-10         	 1751536	      2057 ns/op
profile_java-10                	 2333244	      1541 ns/op
profile_nodejs-10              	 1722144	      2083 ns/op
profile_python-10              	 4395427	       821 ns/op
profile_ruby-10                	 4546932	       793 ns/op
profile_rust-10                	 2960469	      1221 ns/op
```

String matching + sampling:
```
go.cpu.labels.pprof-10        	 2535682	      1415 ns/op
heap-10                       	 7298155	       493 ns/op
dotnet.labels.pprof-10        	 1748709	      2064 ns/op
profile_java-10               	 3828352	       940 ns/op
profile_nodejs-10             	 1721338	      2087 ns/op
profile_python-10             	 7062268	       513 ns/op
profile_ruby-10               	 9947100	       364 ns/op
profile_rust-10               	 2941592	      1225 ns/op

```

I'll go with option 2 (no sampling) for now. It does make things better at times but it increases the likelihood of failures.

**Comment by kolesnikovae** [comment]
Looks good!

Sampling benchmarking vastly depends on the input data. In the worst case, when none of the patterns matches, the benefit will be way more pronounced.

I'm curious how that's possible - I expect that with sampling we only check a few strings randomly (like 10%)
```
go.cpu.labels.pprof-10         	 3418387	      1060 ns/op # String matching (prefix or suffix)
go.cpu.labels.pprof-10        	 2535682	      1415 ns/op # String matching + sampling
```

Anyways, I like your PR, and I'm pretty sure that `GetLanguage` will be barely noticeable. Otherwise, there are ways to improve it further:

We inspect up to N random functions, e.g., 3%. For each selected function:
 - We get extension of the file where it is defined (if the file path is present at all).
 - We check if this is a known extension (no maps, just a global list of extension-language pairs ordered by expected frequency).
 - If there is a match, the language is determined, return.
 - Check known function name prefixes (no maps, just a global list of prefix-language pairs ordered by expected frequency).
 - If there is a match, the language is determined, return.

Optionally, if we're not satisfied with the false-positive rate, we could inspect all the sampled functions and make decision at the end, based on the confidence levels.
