### ISSUE TITLE
Old Version (v0.37.2) documentation could not be found

### ISSUE THREAD

**Issue by argon-kr** [grafana/pyroscope#2779]
we're using version v0.37.2 to use the graphViz feature.
when i visit https://grafana.com/docs/pyroscope to check the server settings, only the v1.x document exists.

where should I check the documentation for check the v0.37.2 settings?

please save me

**Comment by Rperry2174** [comment]
We don't have these published anywhere anymore unfortunately:
https://github.com/pyroscope-io/docs

However, you can run this repo and get the old docs there. Sorry for the inconvenience! We're going to bring this back in the new version, but we wanted to rebuild it in a more sturdy way as the old version had several bugs.

**Comment by argon-kr** [comment]
Thank you for answer! I'll trace the footstep of history
