### ISSUE TITLE
[Golang/PPROF] Show line number and file information in profiles

### ISSUE THREAD

**Issue by pedro-stanaka** [grafana/pyroscope#2891]
#### Is your feature request related to a problem? Please describe.

Golang profiles are very rich in details in regards to code location, it provides code file where the function is defined and also the line of the call for the function being called. When querying profiles in Pyroscope we cant see those information, but it would be really good to see it.

#### Describe the solution you'd like

I would like to see which file and which line that contributed to that profile cell in the Flame Graph.

#### Describe alternatives you've considered

There's nothing much apart from seeing profile files in local, but for that I have to pull the profile from pprof manually.

![image](https://github.com/grafana/pyroscope/assets/2609731/2f64ba73-3248-4ab0-89b5-041b7d3d09b8)

**Comment by kolesnikovae** [comment]
Thank you filing the issue @pedro-stanaka! Probably a dup of https://github.com/grafana/pyroscope/issues/2727 – this is on our plan for next quarter

**Comment by pedro-stanaka** [comment]
Thanks a lot. Will close this one as duplicate.
