### ISSUE TITLE
helm chart not work with customized domain

### ISSUE THREAD

**Issue by paul-hsieh** [grafana/pyroscope#2896]
#### Describe the bug
[`deployments-statefulsets.yaml`](https://github.com/grafana/pyroscope/blob/main/operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml) assumes default domain of `.cluster.local.`.
```
- "-memberlist.join=dns+{{ include "pyroscope.fullname" .}}-memberlist.{{ .Release.Namespace }}.svc.cluster.local.:{{ .Values.pyroscope.memberlist.port }}"
```

This won't work if Kubernetes cluster is deployed with customized domain.

#### To Reproduce
See bug description.

#### Expected behavior
Either:
- Remove `.cluster.local.` from Helm template and delegate DNS resolution to [`resolv.conf`](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#namespaces-of-services).
- Add Helm parameter to allow domain customization.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Helm

**Comment by simonswine** [comment]
This is already worked on in #2684, do you mind to test and comment @paul-hsieh if the current PR would work for you

**Comment by paul-hsieh** [comment]
@simonswine the PR works great, thanks!
