### ISSUE TITLE
flamescope type visualization

### ISSUE THREAD

**Issue by sardarkhanopm** [grafana/pyroscope#2907]
Any idea how we can have flamescope type visualization in pyroscope for selecting timeline, or any plans for same.

![image](https://github.com/grafana/pyroscope/assets/155942993/8e94bcf5-2707-4e1a-8062-1f01108600b8)

flamescope-git - https://github.com/Netflix/flamescope

**Comment by kolesnikovae** [comment]
Hi @sardarkhanopm! This kind of visualisation (sub-second heatmap) is suitable for execution traces that contain low level events such start/stop of execution on a thread, page faults, context switches, and so on. In Pyroscope we deal with a different kind of data – [statistical profiles](https://en.wikipedia.org/wiki/Profiling_(computer_programming)#Statistical_profilers) that represent an aggregation of events. At some point we will add the ability to collect and visualize execution traces, but we don't have any firm plans at this time.

**Comment by sardarkhanopm** [comment]
thanks @kolesnikovae  for clarification.
