### ISSUE TITLE
Add storage based retention

### ISSUE THREAD

**Issue by yasharne** [grafana/pyroscope#291]
Hi
as our services start sending their information to the `pyroscope server` we will face a storage problem although time-based retention is enabled. 
is it possible to also have storage-based retention so that we can always send new information to the server?

**Comment by Rperry2174** [comment]
Hi @yasharne thanks for reporting this, we have also seen a some instances where this would be useful to have for Pyroscope. I've added it to our roadmap and we'll start looking for someone to help contribute to this. 

Let us know if you run into any other issues or have any other requests!

**Comment by kolesnikovae** [comment]
A small update on the size-based retention policy feature: https://github.com/pyroscope-io/pyroscope/pull/431#issuecomment-956179306 - to make long story short, it will require some more time to implement this.

> Along with level-based retention policy, I took an attempt to implement size-based retention. It turned out, it will require significant changes in BadgerDB.
> 
> The approach is very simple – to remove oldest trees calculating the volume of the removed items until the requested space is reclaimed. It is essential to have accurate size estimations of the removed items, the estimation must match occupied disk space.
> 
> I faced the following problems:
> 
> 1. BadgerDB garbage collector reclaims disk space eventually (this is not a problem per se but an aspect of LSM implementation in Badger), making it not possible estimating how much space a particular item occupies on the disk. A naive attempt to fix GC (basically, get rid of many and many heuristics) only slightly improved results. I suspect that SS tables compaction should be also adjusted (an explicit Flatten call is not enough).
> It should be noted that BadgerDB v3 has many improvements in GC area and consumes 2-3 times less disk space. Unfortunately, with BadgerDB v3 server crashes with OOM after short period of time (under standard PR review app load). Perhaps, we should migrate to v3 first; although, this may be complicated by the fact that it is not backward compatible.
>  
> 2. There are 5 databases, 5 independent GC jobs. This fact biases size estimations badly and causes storage to remove way more trees than actually has to. We should unite all databases. 
> 
> The PR contains the code to remove trees from the segment based on the size specified. When we figure out how to make BadgerDB to reclaim disk space on-demand, we can revisit size-based retention feature.
