### ISSUE TITLE
[DOC] Grafana Agent Java Doc and example.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/pyroscope#2927]
#### Is your feature request related to a problem? Please describe.

We should add documentation and example for:

- https://grafana.com/docs/pyroscope/next/configure-client/language-sdks/java/
- https://grafana.com/docs/agent/next/flow/reference/components/pyroscope.java/

**Comment by knylander-grafana** [comment]
We want more doc on how to use this with more examples. We want to to add more content for our Pyroscope section covering Agent features.

**Comment by knylander-grafana** [comment]
Fixes: https://github.com/grafana/pyroscope/pull/2973

**Comment by knylander-grafana** [comment]
It looks like #2973 and #2930 address this doc issue.
