### ISSUE TITLE
[DOC] add example using ebpf and discovery.process

### ISSUE THREAD

**Issue by korniltsev** [grafana/pyroscope#2937]
https://github.com/grafana/pyroscope/issues/2936
- Add example using discovery.process
- Maybe remove undocumented "targets_only" ebpf argument

**Comment by cyriltovena** [comment]
Yes we should remove once it's validated it works and documented.

**Comment by simonswine** [comment]
Also #2946

**Comment by knylander-grafana** [comment]
Done. docs have been updated to use discovery.process for eBPF. These docs are published: https://grafana.com/docs/pyroscope/latest/configure-client/grafana-alloy/ebpf/
