### ISSUE TITLE
display pyroscope data

### ISSUE THREAD

**Issue by ColdV** [grafana/pyroscope#2942]
when i only start Pyroscope service. not send any app profile data to pyroscope.
why i can see the named pyroscope data.
![POPO-screenshot-20240118-171521](https://github.com/grafana/pyroscope/assets/34326084/46995435-852e-4012-910f-59311baf3d60)
how should close it?

**Comment by cyriltovena** [comment]
You can disable self profiling using the config or a flag see https://grafana.com/docs/pyroscope/latest/configure-server/reference-configuration-parameters/#configuration-parameters

Example:

```
-self-profiling.disable-push=true
```

**Comment by bryanhuhta** [comment]
As Cyril noted, we have a configuration which disables this behavior.
