### ISSUE TITLE
Add options to re-enable removed features in flame graph view: filter function table and do not hide narrow call stack bars

### ISSUE THREAD

**Issue by sbrt** [grafana/pyroscope#2970]
#### Is your feature request related to a problem? Please describe.

I used the last released docker image for pyroscope/pyroscope and was very happy with it.
Trying out the most recent grafana/pyroscope image left me disappointed about several UI changes that severely limit usability for my use case. In my company I profile reactive R shiny apps, which definitely is not your usual use case, but since my only reservations are about removal of features (or lack of choice), maybe you can consider adding UI elements to re-enable these features:

* I think you have tried to make the flame graph less "busy" by not showing labels at all for narrow pats of some call stack "peaks". However, in my case, these hidden peaks contain most of the information and this makes it harder to assess where my app is spending its time. It also does not help that tooltips don't show for these hidden peaks.

* You no longer filter the function table when one searches in the flame graph view.

#### Describe the solution you'd like

Add UI elements to enable these features on-demand.

#### Describe alternatives you've considered

I am now using grafana/pyroscope:1.2.0, that is fine for my purposes.

**Comment by bryanhuhta** [comment]
It's true that we  we compress small flamegraph nodes together for performance reasons. We're actively working on a fix to make this configurable so users can select a node resolution of their choice.

If you're using `grafana/pyroscope`, you can get around this by adding `max-nodes=<some big number>` or (`max-ndes=-1` to disable node limits entirely). Note there may be a query performance penalty by doing this though.

**Comment by sbrt** [comment]
Thank you very much for the prompt response, that's already a really great help!
