### ISSUE TITLE
Add export to pprof

### ISSUE THREAD

**Issue by sbrt** [grafana/pyroscope#2971]
#### Is your feature request related to a problem? Please describe.

Pyroscope is great for continous profiling and aggregation, but pprof is still more feature rich for analysis in my opinon. 

#### Describe the solution you'd like

Add export to pprof format for the query selection, so one can easily use both until pyroscope is a full replacement.

**Comment by bryanhuhta** [comment]
> Add export to pprof format for the query selection, so one can easily use both until pyroscope is a full replacement.

Can you expand on this?

We have an option to export pprof data. If you navigate to "single view" mode and apply a query, there's an option to download the query results to a few different formats.

<img width="438" alt="Screenshot 2024-01-26 at 4 31 18 PM" src="https://github.com/grafana/pyroscope/assets/32787160/d3c19f19-2520-4171-a375-d6352a6a9db3">

**Comment by sbrt** [comment]
Okay, sorry! I might have mixed up versions, I was using pyroscope/pyroscope until recently.
