### ISSUE TITLE
Don't try delete old ingester blocks without bucket store configured

### ISSUE THREAD

**Issue by bryanhuhta** [grafana/pyroscope#2974]
When running Pyroscope without bucket storage configured (this typically occurs when running locally in monolith mode), the ingester block cleaner tries to clean blocks off disk. However, since a shipper isn't running, no `shipper.json` file is created and the cleaner logs the following error:

```
ts=2024-01-29T12:54:11.499628801Z caller=retention.go:147 level=error msg="failed to delete uploaded blocks, could not get blocks for tenant" err="open data/anonymous/local/shipper.json: no such file or directory" tenantID=anonymous
```

We should account for `shipper.json` not existing by turning off the block cleaner. We should also log a warn level message (or no message at all) when this occurs instead of an error, since it's not exactly an error scenario.

**Comment by kolesnikovae** [comment]
I think we should not turn off the block cleaner unless it's disabled explicitly via config. The primary purpose of the cleaner is to avoid is to prevent data loss due to lack of the available disk space, and this does not depend on whether an object storage backend is configured or not

**Comment by weastel** [comment]
Make Sense @kolesnikovae, what is expected behaviour then? Should we able to delete blocks when high disk utilisation but stop deleting behaviour for blocks uploaded, as no blocks will be uploaded to storage bucket. For reference.

```go
deleted = dc.DeleteUploadedBlocks(ctx)
level.Debug(dc.logger).Log("msg", "cleaned uploaded blocks", "count", deleted)

deleted, bytesDeleted, hasHighDiskUtilization = dc.CleanupBlocksWhenHighDiskUtilization(ctx)
if hasHighDiskUtilization {
	level.Debug(dc.logger).Log(
		"msg", "cleaned files after high disk utilization",
		"deleted_blocks", deleted,
		"deleted_bytes", bytesDeleted,
	)
} 
```

**Comment by weastel** [comment]
Updating PR by above assumption

**Comment by kolesnikovae** [comment]
Thank you so much for the contribution @weastel! We'll review the changes today-tomorrow.

I think that these are two independent processes (but synchronized):
1. Removal of the uploaded blocks: our goal here is to lower the requirements for the disk capacity
2. Removal of the historical data when there is not enough space for new data: the purpose is to prevent failure / data loss

Basically, `HighDiskUtilization` removal should be happening regardless of the block upload status: any block is deletable when there is no space
