### ISSUE TITLE
Pyroscope agent high CPU consumption

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/pyroscope#307]
A separate issue for the problem revealed in https://github.com/pyroscope-io/pyroscope/issues/294.

----

**But more importantly, over time, the agent takes more and more CPU times.**
We have three servers. `basic-exp-logic1` and `basic-exp-logic2` was profiling by  pyroscope, it consumes more CPU.
![](https://user-images.githubusercontent.com/15027927/127314544-7121d908-7d2c-4611-9ab8-66e6123fac60.png)

Compare by Pyroscope UI. `ProfileSession taskSnapshots()` is taking more and more CPU.
![image](https://user-images.githubusercontent.com/15027927/127090642-d679c812-3bd1-4e68-921b-adeabb56a2a7.png)

Server: 4vcpu8G.
Config: 
  DisableGCRuns: true
  SampleRate: 20

So, is it normal?
Thank you!

_Originally posted by @hiyanxu in https://github.com/pyroscope-io/pyroscope/issues/294#issuecomment-887180487_

**Comment by hiyanxu** [comment]
Hi,
  Could you replace the first picture with another picture? Because I made some mosaics in original picture of #294 .

Thank you very much!😁

**Comment by kolesnikovae** [comment]
@hiyanxu, thank you for reporting the issue! I'd like to clarify the version of Pyroscope Agent and Go you run.

Also, continuing our previous discussion, did changes in # 303 help in any way?

**Comment by hiyanxu** [comment]
@kolesnikovae 
The version of Pyroscope Agent and Go:
    Pyroscope Agent: v0.0.35
    Go: go1.14.15

Because it's a production environment, I can't try it casually, so I'm not sure whether it's effective.
Sorry~

**Comment by kolesnikovae** [comment]
@hiyanxu, could you please confirm if the issue persists with default `SampleRate`? Unfortunately, I didn't manage to reproduce the problem. Is there anything special with the profiled application?
