### ISSUE TITLE
[DOC]The pyroscope ui in the document does not appear to be consistent with the actual one

### ISSUE THREAD

**Issue by shenqidebaozi** [grafana/pyroscope#3129]
The pyroscope ui in the document does not appear to be consistent with the actual one
https://grafana.com/docs/pyroscope/latest/view-and-analyze-profile-data/pyroscope-ui/

![image](https://github.com/grafana/pyroscope/assets/35397691/93a5bb4e-ae8c-450d-ad8c-cfab18425ad6)
actually：
<img width="1686" alt="image" src="https://github.com/grafana/pyroscope/assets/35397691/a944e42c-c4af-48ea-9872-511d88fd944f">

Did I miss any information? Do have any plans to implement full functionality in Grafana, such as Diff? This way, users can only follow the Grafana dashboard

**Comment by knylander-grafana** [comment]
PR in Pyroscope: https://github.com/grafana/pyroscope/pull/3234

I've also updated the Pyroscope UI content for the Grafana Cloud Profiles documentation.
