### ISSUE TITLE
S3 storage, can the same bucket be specified with different paths?

### ISSUE THREAD

**Issue by ly0511** [grafana/pyroscope#3151]
#### Describe the bug
Our service has many partitions, and each partition needs to obtain performance data. When using s3 storage, does the same bucket support storing data according to different paths instead of creating multiple s3 buckets?

#### Environment

- Infrastructure: [Kubernetesop]
- Deployment tool: [ helm]

**Comment by simonswine** [comment]
No that is not supported. You are expected to sent all your profiles to a central deployment of Pyroscope.
