### ISSUE TITLE
[doubt] eBPF with Grafana Agent using on K8s

### ISSUE THREAD

**Issue by fvmiranda** [grafana/pyroscope#3163]
## Doubt about eBPF usage

Hello guys, I am trying to configure Pyroscope on a EKS Cluster using de Deployment via Helm as the docs says.

I have the following scenario, I'm already using Grafana Stack (Mimir, Loki and Tempo) with Open Telemetry and using the Nodejs and .NET SDKs for instrument my apps.

I would like to know if for Pyroscope using the Grafana Agent I will have auto Instrumentation for all my Apps (.NET and Nodejs)  without doing any code, just using eBPF.

The following image shows my current k8s nodes version.
![image](https://github.com/grafana/pyroscope/assets/143446527/1c1957ea-5328-48f6-94ed-2d77637685b0)

**Comment by Rperry2174** [comment]
Unfortunately we do not support node and .net yet -- however we are very actively involved in the[ OTel efforts](https://opentelemetry.io/blog/2024/profiling/) with providing an agent that will support these languages. 

you can see a list of the languages we do support via grafana agent[ here ](https://grafana.com/docs/pyroscope/next/configure-client/grafana-agent/ebpf/configuration/#supported-languages)

**Comment by fvmiranda** [comment]
Thank you for your quickly response!
