### ISSUE TITLE
How run pyroscope agent with IIS

### ISSUE THREAD

**Issue by mohrmz** [grafana/pyroscope#3261]
#### Describe the bug
I want to deploy my asp.net core application with iis
as [pyroscope documentation](https://pyroscope.io/docs/dotnet/) says i shoud run .net app
with 
pyroscope exec myapp.exe "arg1" "arg2"

how can i run this command with pyroscope agent in iis

**Comment by korniltsev** [comment]
May I ask where did you find ` pyroscope exec myapp.exe "arg1" "arg2"` ?

**Comment by kolesnikovae** [comment]
Hi @mohrmz, unfortunately, as of now dotnet profiler is only supported on linux amd64. If you want to profile .net apps on Windows, please create a new issue

**Comment by mohrmz** [comment]
> Hi @mohrmz, unfortunately, as of now dotnet profiler is only supported on linux amd64. If you want to profile .net apps on Windows, please create a new issue

Hi @kolesnikovae I oen new feature request issue at https://github.com/grafana/pyroscope/issues/3263

**Comment by kolesnikovae** [comment]
Thank you @mohrmz! We'll look into it and prioritize accordingly
