### ISSUE TITLE
Doesn't work with Python3.12

### ISSUE THREAD

**Issue by fnmut** [grafana/pyroscope#3287]
#### Describe the bug
I don't believe this is working with Python3.12, is that right?

#### To Reproduce

The example referenced [here](https://github.com/grafana/pyroscope/blob/main/examples/language-sdk-instrumentation/python/simple/main.py) uses Python 3.11, and it works with 3.11

When I use Python 3.12 I get stuck on `Pyroscope::Session > Creating Session`

#### Expected behavior

Profiles get sent to a local server using python 3.12

#### Environment

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm, jsonnet]

#### Additional Context

Any plans to support Python 3.12? Is there something I can do to get it working?

**Comment by korniltsev** [comment]
There is pyspy issue https://github.com/benfred/py-spy/issues/633

In the meantime, you can try using `grafana-agent` / `alloy` . They can profile python apps with `pyroscope.ebpf` component

**Comment by we684123** [comment]
py-spy [Releases v0.4.0](https://github.com/benfred/py-spy/releases) 
Python 3.12、3.13 Support

**Comment by mtralka** [comment]
`py-spy=0.4.0` and `pyroscope-io=0.8.7`continue to be stuck on `Pyroscope::Session > Creating Session` for me using the [toy example](https://github.com/grafana/pyroscope/blob/main/examples/language-sdk-instrumentation/python/simple/main.py). 

I can confirm py-spy is working as expected without Pyroscope

**Comment by korniltsev** [comment]
Fixed by https://github.com/grafana/pyroscope-rs/pull/181 in  the pip package v0.8.8
