### ISSUE TITLE
Support for EKS Pod Identity

### ISSUE THREAD

**Issue by mogopz** [grafana/pyroscope#3459]
#### Is your feature request related to a problem? Please describe.

Hello! It would be great if Pyroscope worked with the new(ish) EKS feature [Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html). I've just tried to use it but I _think_ the AWS SDK version being used is [too old](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html) so I was getting Access Denied errors and had to revert to using IRSA instead.

#### Describe the solution you'd like

The ability to map roles to Pyroscope pods using Pod Identity instead of IRSA.

#### Describe alternatives you've considered

We're currently using IRSA instead which works fine, but Pod Identity is preferred 😁

**Comment by simonswine** [comment]
This should be working after #3465 has merged.
