### ISSUE TITLE
The tenant-setting has been re-added to the micro-service

### ISSUE THREAD

**Issue by be-hase** [grafana/pyroscope#3463]
This PR should have removed it once, but it seems to have been added again recently.
Was this an intentional change? (It doesn't seem to be related to Grafana Cloud.)

- https://github.com/grafana/pyroscope/pull/2922
- https://github.com/grafana/pyroscope/pull/3417

**Comment by simonswine** [comment]
@be-hase thanks for highlighting this. In the mean time we have open sourced the frontend https://github.com/grafana/explore-profiles, which is using that settings API and so it is relevant for the OSS version of Pyroscope.

**Comment by be-hase** [comment]
Oh! I don't fully understand the details yet as I couldn't find the document, but it's good if there are no issues!
