### ISSUE TITLE
I want to change the storage method to S3, but it didn't take effect.

### ISSUE THREAD

**Issue by wenwenGeek** [grafana/pyroscope#3508]
pyroscope version : 1.7.1
i use pyroscope_1.7.1_linux_amd64.tar.gz 
After extraction, a file named "pyroscope.yaml" was created in the current directory.
<img width="232" alt="image" src="https://github.com/user-attachments/assets/0c601f41-6bb2-47d4-9319-28e5452e7116">

console output 
<img width="2995" alt="image" src="https://github.com/user-attachments/assets/35e87509-42e5-4c21-a8b8-c7994768283d">

Pyroscope Admin page 
<img width="521" alt="image" src="https://github.com/user-attachments/assets/e2196010-2b69-4a06-83fb-a9b01935308d">

```[tasklist]
### Tasks
```

**Comment by kolesnikovae** [comment]
Thanks for reporting the issue.

The configuration file path should be specified explicitly via the `--config.file={path}` flag.

**Comment by wenwenGeek** [comment]
thank you，

**Comment by wenwenGeek** [comment]
I have another question: When multiple servers use the same S3, is the data shared?

**Comment by kolesnikovae** [comment]
Yes, this is supposed to be used as a shared storage: all the components of the architecture should have access to the same bucket.

However, please note that ingesters do need local persistent storage: by default, blocks of data are uploaded to object storage every hour. If you need to ensure high availability, you need to deploy multiple ingester instances. You can find more information about this in our docs: https://grafana.com/docs/pyroscope/latest/reference-pyroscope-architecture/about-grafana-pyroscope-architecture/

**Comment by kolesnikovae** [comment]
If you don't mind, I'm closing the issue
