### ISSUE TITLE
I have two Pyroscope nodes,What configuration can I change to enable faster data synchronization between them?

### ISSUE THREAD

**Issue by wenwenGeek** [grafana/pyroscope#3510]
I have two Pyroscope nodes, namely Node A and Node B. Data is collected using Alloy and reported to Node A, with storage using S3. The information synchronization delay for Node B is significant, currently around 2 hours. What configuration can I change to enable faster data synchronization between them?

<img width="2881" alt="image" src="https://github.com/user-attachments/assets/30192cbf-7cec-4a05-b947-1516659ec8ff">
<img width="526" alt="image" src="https://github.com/user-attachments/assets/777690b0-a75a-44a9-8f3a-667e0a12ef71">

**Comment by kolesnikovae** [comment]
Hi @wenwenGeek!

The current architecture assumes that you send data to distributors (random instance), which then replicate the request among ingesters – this is known as [optimistic replication](https://en.wikipedia.org/wiki/Optimistic_replication). After a certain period of time (approximately 1 hour), blocks of data are uploaded to long-term object storage, and compacted/optimized in the background. Until that point, the data is queried from ingesters. There is no synchronization between ingester nodes, as they store the data locally.

Also, please note that in a distributed scenario, you need at least 3 ingesters for high availability. Please refer to [Grafana Pyroscope Architecture](https://grafana.com/docs/pyroscope/latest/reference-pyroscope-architecture/about-grafana-pyroscope-architecture/).
