### ISSUE TITLE
The Helm chart corresponding to version 1.9.0 has not been released

### ISSUE THREAD

**Issue by be-hase** [grafana/pyroscope#3609]
I would appreciate it if you could release it.

https://github.com/grafana/pyroscope/blob/v1.9.0/operations/pyroscope/helm/pyroscope/Chart.yaml#L5-L6

**Comment by aleks-p** [comment]
Hi @be-hase, thanks for reporting this.

We've hit a little snag with our release pipeline, which is why the chart was not fully published. We are actively working on resolving this!

cc @marcsanmi

**Comment by sleterrier** [comment]
Hey @aleks-p, any news on releasing a Helm Chart > 1.7.1?

**Comment by marcsanmi** [comment]
Hi @sleterrier, we're working on it and it shouldn't take longer than this week 🙂

**Comment by sleterrier** [comment]
Thank you for the quick answer @marcsanmi, much appreciated 🙇

**Comment by marcsanmi** [comment]
New helm chart has been released, you can check it [here](https://github.com/grafana/helm-charts/releases/tag/pyroscope-1.9.1).

Thank you all.
