### ISSUE TITLE
Pyroscope store data in a specific directory of s3 bucket

### ISSUE THREAD

**Issue by pyhita** [grafana/pyroscope#3670]
We use s3 bucket as the backend storage of pyroscope, but there are other applications that use the same bucket as us, so we want to set pyroscope to store data in a specific directory of the bucket, but we did not find the appropriate configuration items in "s3_storage_backend" part to accomplish this.

We want to config like this:
```bash

storage:
  backend: s3
  s3:
    bucket_name: "grafana-pyroscope-data/apm/data"
........
```
But pyroscope starts failed and prints "Bucket name contains invalid characters".We would like to know whether pyroscope can store data in a bucket-specific directory. If so, how should it be configured?

**Comment by talmalka4** [comment]
you can use 
storage:
  storage_prefix: <env>

**Comment by pyhita** [comment]
> you can use
> 
> ```
> storage:
>   storage_prefix: <env>
> ```
It works for me! ths!
