### ISSUE TITLE
Dotnet Language SDK example not working

### ISSUE THREAD

**Issue by AstralJaeger** [grafana/pyroscope#3680]
#### Describe the bug
The DotNet Language SDK example isn't working. After running the example using ``docker compose up`` I'm not getting any profiles from the applications in Pyroscope, only the Pyroscope self-profiling. Application also doesn't log ``ENV PYROSCOPE_APPLICATION_NAME=fast-slow.dotnet.app`` from dockerfile, but instead logs ``unknown_service:dotnet``.

#### To Reproduce

1. Clone the repository
2. Navigate to the example folder ``examples\language-sdk-instrumentation\dotnet\rideshare``
3. run ``docker compose up`` 
4. observe the profiles collected in the pyroscope frontend ``localhost:4040``

#### Expected behavior
To get the profiles of the instrumented application and the correct PYROSCOPE_APPLICATION_NAME is logged on the console.

#### Environment

- Infrastructure: Docker Compose on Docker Desktop
- Deployment tool: VSCode, Docker, Windows

#### Additional Context

Screenshot of logs:
![Image](https://github.com/user-attachments/assets/40b13c69-f4b9-40bb-84c9-a446a4758637)

Applications in Pyroscope:
![Image](https://github.com/user-attachments/assets/2d6f5741-b9f6-4ca3-ad22-539cba8163dc)

A little support here would be nice, I've tried to instrument my own application using Pyroscope and had issues and thus tried to run the dotnet rideshare example but I'm having the same issues. Issues occur on Kubernetes, Docker Desktop (Windows) and Docker Desktop (MacOS)

**Comment by AstralJaeger** [comment]
Update:
The rideshare example works with verison 0.8.20 of the pyroscope profiler, but not with version 0.9.0

**Comment by korniltsev** [comment]
>  The rideshare example works with verison 0.8.20 of the pyroscope profiler, but not with version 0.9.0
I will take a look

**Comment by korniltsev** [comment]
for history, the error is 

```
[2024-11-22 10:51:20.531 | warning | PId: 7 | TId: 7] Profiling is disabled: It appears the wrapper library 'Datadog.Linux.ApiWrapper.x64.so' is not correctly loaded.
Possible reason(s):
* The LD_PRELOAD environment variable might not contain the path '/dotnet/Datadog.Linux.ApiWrapper.x64.so'. Try adding '/dotnet/Datadog.Linux.ApiWrapper.x64.so' to LD_PRELOAD environment variable.
* Your application might be running in a secure execution mode (false). Try adding the path '/dotnet/Datadog.Linux.ApiWrapper.x64.so' to the /etc/ld.so.preload file (create the file if needed).
If the issue persists, please contact the support with the following details:
LD_PRELOAD current value: /dotnet/Pyroscope.Linux.ApiWrapper.x64.so
The process running in a secure execution mode: false
Process User ID differs from Effective User ID: false
Process Group ID differs from Effective Group ID: false

```
