### ISSUE TITLE
Profiling python web frameworks

### ISSUE THREAD

**Issue by raqibhayder** [grafana/pyroscope#428]
Amazing work with Pyroscope. 👏🏽 

Is there a way to profile web frameworks like FastAPI, Starlette or Flask? 

We are currently using new relic and were testing out Pyroscope as an alternative for performance monitoring. We are using [`gunicorn` with `UvicornWorkers`](https://www.uvicorn.org/deployment/#gunicorn) and `FastAPI` as our framework using the following docker [image](https://fastapi.tiangolo.com/deployment/docker/#tiangolouvicorn-gunicorn-fastapi).

We are able to see all `gunicorn`, `uvicorn` and our application function calls but unable to see anything related to Starlette (the framework FastAPI is wrapped around), specifically Starlette middleware calls.

I feel like I am missing something silly here, any help would be appreciated.

Thank you 😄

**Comment by petethepig** [comment]
Hi @raqib-hayder 

Thanks for the kind words :)

Pyroscope should work great with the use-case you're describing and should generally work with any framework like `gunicorn`. 

This might be related to the way subprocesses / forks are treated by the pyroscope agent. I can try to reproduce the issue with the docker image you linked and see if there's a bug somewhere. 

The only question I have right now is how are you integrating with pyroscope? Are you running it via `pyroscope exec` or the pip package (`pyroscope-io`)?

**Comment by raqib-hayder** [comment]
@petethepig : We are using the pip package `pyroscope-io`.

**Comment by raqib-hayder** [comment]
@Rperry2174 and @petethepig : Thank you for updating the example. Will give this a try and let you guys know how it went. Much apprecaited.

**Comment by raqib-hayder** [comment]
You guys are awesome! Thank you for promptly looking into this.

**Comment by petethepig** [comment]
Hi @raqib-hayder 

We just released a new version of the pip package (0.4.0) with a fix for this issue.

Let me know if you have experience it.
