### ISSUE TITLE
Translate docs to other languages

### ISSUE THREAD

**Issue by Rperry2174** [grafana/pyroscope#46]
We're getting a lot of users from other countries all over the world, particularly China and would love for everyone to be able to access our docs / how to use Pyroscope more easily. 

Any help translating to any language would be awesome! For right now we are hoping to get the following translated:

- [Main README](https://github.com/pyroscope-io/pyroscope/blob/main/README.md)
- [Examples page](https://github.com/pyroscope-io/pyroscope/tree/main/examples)
- [Debug Python with Pyroscope](https://github.com/pyroscope-io/pyroscope/blob/main/examples/debug_python_with_pyroscope.md)

**Comment by petethepig** [comment]
Please add languages you'd like to see here. We're currently working on these translations:
* [x] Chinese
* [ ] Russian
