### ISSUE TITLE
Refactor HTTP backend code

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#479]
As our HTTP backend code complexity increases we need to find better ways of organizing that code. Currently we're only using standard golang `net/http` package and we're already seeing some limitations of it, for example, `handleFunc("/", ...)` matches everything after `/`, not just `/`, so we have to work around it (https://github.com/pyroscope-io/pyroscope/blob/separate-client-module/pkg/server/handler.go#L198-L209)

There are other issues with it as well, we'll document them as we start working on this issue.

#### Tentative TODO:
* [x] add some framework (maybe gorilla?)
* [ ] add endpoints for the stuff that's server renderer (notifications, build info etc)
* [ ] move all api endpoint calls under /api
* [ ] add more tests for backend api

**Comment by abeaumont** [comment]
some work in this direction has been done already: gorilla framework was added in https://github.com/pyroscope-io/pyroscope/pull/624, which also includes a new `adhoc` API following using the proposed format (the new `adhoc` API is under `/api/adhoc` and their route handling is decoupled from the _main_ controller).
