### ISSUE TITLE
Make deeply nested highlighted nodes visible

### ISSUE THREAD

**Issue by waywardmonkeys** [grafana/pyroscope#526]
When selecting an item in the table, it would be nice for there to be a way to find it easily even in a deeply nested flamegraph.

**Comment by eh-am** [comment]
You are absolutely right @waywardmonkeys!
Would https://github.com/pyroscope-io/pyroscope/issues/500 be more or less what you have in mind?

**Comment by waywardmonkeys** [comment]
Not exactly. I mean, that wouldn't hurt, but even when I type the name of a function in the highlight, I'm not seeing anything in the flame graph for things that are small and deeply nested. Something near top-level, sure ...

**Comment by eh-am** [comment]
I think this is a good exemplification of the issue @waywardmonkeys brought up:
![Peek 2021-11-24 16-42](https://user-images.githubusercontent.com/6951209/143303488-c8892c03-9ecc-4fac-8a6d-513eeddd1078.gif)

**Comment by Rperry2174** [comment]
@eh-am I ran into this recently and was thinking we could also maybe outline the parent node instead of highlighting it in these cases
