### ISSUE TITLE
Make storage parameters configurable

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/pyroscope#589]
Users should be able to change hardcoded storage parameters:
https://github.com/pyroscope-io/pyroscope/blob/141d73406f5482ee14f999ee7721403d3e0d3d99/pkg/storage/storage.go#L80-L94

**Comment by ItsATrap48** [comment]
@kolesnikovae can I take this one on?

**Comment by kolesnikovae** [comment]
@ItsATrap48, I would really appreciate your help!

I think we should add a new nested structure in the storage config so that the new configuration options would have some common prefix, e.g: `--storage.badger-gc-size-diff` (`PYROSCOPE_STORAGE_BADGER_GC_SIZE_DIFF`). Not quite sure if those should be listed in the CLI help message, as these are intended for fine tuning and debug purposes – in my opinion it's okay if they won't be displayed; we can always fix it when needed.

The current values can be taken as default ones. We may also need to define behaviour for zero values explicitly. For example, it may make sense disabling a maintenance task, if its interval is set to 0 (could be helpful in some cases, I believe). Though, it's okay to consider such an input incorrect and not start the server, but return an error message to the user.

Please me know if you need more details :)

**Comment by ItsATrap48** [comment]
@kolesnikovae which struct are you saying we should add a new nested structure to? Is there somewhere else in the code you want the new values to be taken in from?  Sorry this issue may be too advanced for me.

**Comment by kolesnikovae** [comment]
@ItsATrap48, I assume that we can extend [`config.Server`](https://github.com/pyroscope-io/pyroscope/blob/58969821013f15b8f2f425e9d2ffa855f615d8a3/pkg/config/config.go#L93) type:

```go
type Server struct {
    Storage `mapstructure:"auth"`
    // Remaining params.
}

type Storage struct {
    BadgerGCTaskInterval time.Duration
    // All the rest storage config options.
}
```

Notice field tags in the structures – they control many things, but we are particularly interested in the following:
 - `mapstructure` - field name (both CLI flag and in YAML file).
 - `deprecated: true` - won't show the field in the help message.
 - `desc` - human-friendly description, can be omitted if `deprecated`.
 - `def` - default value.

This will also require some changes in `storage` package, mostly this function: https://github.com/pyroscope-io/pyroscope/blob/58969821013f15b8f2f425e9d2ffa855f615d8a3/pkg/storage/config.go#L24 and the constructor:
https://github.com/pyroscope-io/pyroscope/blob/58969821013f15b8f2f425e9d2ffa855f615d8a3/pkg/storage/storage.go#L82 where all the default values are hardcoded. I think that making these params configurable is enough.

Please don't worry about the complexity, I'll gladly help you to get into it and answer any questions :) Also, if you need this feature urgently, just let us know and we'll prioritize it accordingly.

@petethepig, what would you say? We already have some storage params at the root level (e.g. `cache-evict-threshold`) therefore it may make the config a bit less consistent. On the other hand, perhaps it's better than the `config.Server` type bloating.
