### ISSUE TITLE
Auto-collapse flamegraphs

### ISSUE THREAD

**Issue by petethepig** [grafana/pyroscope#595]
Many flamegraphs, particularly ones from ruby or python apps include a lot of intermediary library-type calls that just delegate things down the stack and that information is often not very useful. You especially get a lot of this when using tags.

We could implement some algorithm that would detect those situations and instead of rendering the whole stacktrace render just one special node that a user could click to expand.

Here's a rough mockup of what I have in mind:

### Before

![before](https://user-images.githubusercontent.com/662636/145321695-e7b0277f-4e78-415b-bbd2-618fabc72724.png)

### After
![after](https://user-images.githubusercontent.com/662636/145321706-26ca5dd6-6681-47a9-88a4-8d0ea04183c2.png)

When you click on the node it gets expanded and looks just like the one in before picture

**Comment by eh-am** [comment]
Interesting idea, but I am having trouble visualizing what would the heuristic be. Would it be tailored per framework?

**Comment by Rperry2174** [comment]
yeah I agree @eh-am. I think it would have to be per-framework and we would probably have to write some sort of "plugin" type of thing where it filters out certain chunks depending on which framework it is... No way we can support _all_ frameworks for this, but if we build it in a way where community members can contribute for the frameworks that are important to them then that could work

**Comment by nornagon** [comment]
could this data be added by clients at ingestion time? e.g. add an optional "collapse tag" to each stack frame. then it could be up to the client to add this data.

**Comment by EraYaN** [comment]
I do think it would be valuable to have some automatic stuff server-side for usability sake, .NET ASP.NET Core apps have a ton of this as well. Especially with async code, it will have 100 lines of which 4-10 are interesting. This might even be purely front-end UI code.

every single

```
System.Runtime.CompilerServices*
System.Threading.*
System.Net.Sockets*
```
etc.
And arguably all the Kestrel and other Http and Async handling stuff as well.

**Comment by nornagon** [comment]
I don't think #595 is related to this..?
