### ISSUE TITLE
feat: grafana plugins  pyroscope-datasource cannot use grafana templating variables.

### ISSUE THREAD

**Issue by linthan** [grafana/pyroscope#647]
we need to use grafana to display pyroscope data。 accodring to  different application, there are different profile data。
application need to be a variable so that  we can easily to display different application's profile data.

![image](https://user-images.githubusercontent.com/13914829/147238023-c084a1d0-6471-4d22-acc1-886076ba426b.png)

**Comment by eh-am** [comment]
Hey, good news! We are working on this right now:
https://github.com/pyroscope-io/grafana-datasource-plugin/pull/2

Should be available soon!

**Comment by linthan** [comment]
@eh-am  could you tell me when this feature comes up? currently，it seems that it doesn't work correctly with  the  v0.5.1 of
pyroscope.

**Comment by linthan** [comment]
pyroscope panel plugin 
1.0.1 cannot display unit correctly
![image](https://user-images.githubusercontent.com/13914829/147426233-7be068a5-6444-4904-bda4-a22c11a52320.png)
![image](https://user-images.githubusercontent.com/13914829/147426316-76ccc912-1b02-475b-8fd1-dbbe04361c77.png)

1.1.0 
cannot display.  

pyroscope is the v0.5.1

**Comment by linthan** [comment]
![image](https://user-images.githubusercontent.com/13914829/147429657-870e123a-c8b0-4ef9-ae90-baae0f77c08a.png)
you need to add metadata's attributes  to the flamebearer object.
