### ISSUE TITLE
Improve Table rendering speed time

### ISSUE THREAD

**Issue by eh-am** [grafana/pyroscope#702]
[`TableBody`](https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/ProfilerTable.jsx#L209) seems quite slow to render:

![image](https://user-images.githubusercontent.com/6951209/148979558-d03e7975-38b6-499c-a5bf-eb81c427677a.png)

Which makes everything else in the `FlamegraphRenderer` tree also sluggish.
It's a good idea to investigate it and improve it.

**Comment by Rperry2174** [comment]
Would it help if we paginated the table? i.e. just show the first 25 rows or something or is this some other issue?

**Comment by eh-am** [comment]
@Rperry2174 honestly I don't know, but I don't think that's the problem. My guy feeling says it's something silly we are doing wrong, something that's just a matter of sitting down and debugging it.
