### ISSUE TITLE
Cannot open the site tips 404

### ISSUE THREAD

**Issue by seaurching** [grafana/pyroscope#709]
I configured the base-url to `/pyro` , it tips me `404 not found` with url `http://ip_address:4040/pyro` or `http://ip_address:4040/pyro/`.
How to use it

**Comment by eh-am** [comment]
Hey, thank you for trying pyroscope!

So the way it works is that the server is still served under `http://ip_address:4040`, the only difference is that the links assume it will be served under `/${baseUrl}`.

I've pushed an example here https://github.com/pyroscope-io/pyroscope/pull/710
Let me know if you have any questions!
