### ISSUE TITLE
Add autocomplete to grafana-datasource

### ISSUE THREAD

**Issue by eh-am** [grafana/pyroscope#711]
As of version v1.1.0 we have a naive autocomplete that doesn't take tags in consideration.

It's a good idea to make it a full fledged autocomplete. Which could be used for the main pyroscope all as well.

https://community.grafana.com/t/how-to-add-a-resource-handler-for-your-data-source/58924

**Comment by Leegin-darknight** [comment]
When we have 1000s of services and pods it would be tough to remember the names of the services to query. If we get full-fledged autocomplete or get all the tags in the drop-down it will improve the ease of use via Grafana.
