### ISSUE TITLE
Maximum resolution/frequency of profiles supported  

### ISSUE THREAD

**Issue by drahnr** [grafana/pyroscope#901]
As part of the discussion in https://github.com/pyroscope-io/pyroscope-rs/pull/21 , it would be great to understand the limitations of the frequency that a profile can be posted by an agent to the backend. The granularity does matter for some usecases.

**Comment by omarabid** [comment]
Also related: https://github.com/pyroscope-io/pyroscope/issues/900

**Comment by ordian** [comment]
@petethepig thank you for the reply. Could you point us to changes needed on the server side? It seems more than just one constant change.

> if the change is not too drastic (e.g from 10 to 1 second) 

We're actually thinking of 1-2 seconds :) 

>  I'm curious where you're coming from and what kind of problems you're hoping to solve with Pyroscope.

We want to profile a critical section which spans 2 seconds. And to do it continuously to track perf regressions in the future as well to see how it performs under real world workload.

**Comment by AndreiEres** [comment]
> After you do that you'll have to deal with the same frequency being hardcoded on the server side.

@petethepig I'm wondering, how it works with eBPF agent. It has a 15s `collect_interval` according to its [docs](https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/ebpf/#configuration).

**Comment by yanns** [comment]
Is it possible to provide an explanation why this issue is closed?
It is because it is implemented? Was the 10s frequency on the server side made configurable somehow?
Or is it because it's unlikely to ever be implemented?

**Comment by CloudOfEquality** [comment]
Any idea to set Pyroscope resolution from the user perspective now?
Seems still no access to that both in pyroscope command line tool and in the yaml config params
